import { defineLesson } from './lesson-format.js';

export const homeLessons = {
  D07: defineLesson('D07', {
    scenario: '在家准备番茄炒蛋和米饭。你负责淘米，朋友负责洗切蔬菜；鸡肉是另一天的食材，尚未解冻，需要另作安排。',
    phrases: ['rinse the rice 淘米', 'peel the potatoes 削土豆皮', 'chop it up 切碎', 'slice it thinly 切薄片', 'thaw in the fridge 在冰箱里解冻', 'set it aside 放在一旁备用'],
    core: [
      ['Could you wash the vegetables?', '你能洗一下蔬菜吗？', '我'],
      ["I'll rinse the rice first.", '我先淘米。', '我'],
      ['Could you chop these up while I wash the rice?', '我淘米的时候，你能把这些切好吗？', '我', 'these 需要明确指向眼前的食材；chop up 通常指切成小块。'],
      ['How small do you want the pieces?', '你想切成多小的块？', '朋友'],
      ['Small chunks are fine.', '切成小块就行。', '我'],
      ['Could you slice the onion thinly?', '你能把洋葱切成薄片吗？', '我', 'slice 侧重切成片；chop 常用于切块或切碎，需要补充大小。'],
      ['Do we need to peel these?', '这些需要去皮吗？', '朋友'],
      ["Let's set that aside for now.", '我们先把那个放一边备用。', '我'],
      ['The chicken is still frozen.', '鸡肉还冻着。', '朋友'],
      ["Let's let it thaw in the fridge for tomorrow.", '让它放在冰箱里解冻，明天再用吧。', '我', '本句是安排明天的食材；不示范把生肉长时间放在室温解冻。'],
      ['Use a separate cutting board for the raw meat.', '生肉用另一块砧板。', '我'],
      ["What should I do next?", '我接下来做什么？', '朋友'],
    ],
    dialogues: [
      ['分配备菜工作', '确认动作和切块大小', [
        ['我', "I'll rinse the rice. Could you wash the tomatoes?", '我来淘米，你能洗一下番茄吗？'],
        ['朋友', 'Sure. Should I chop them up too?', '可以，也要切好吗？'],
        ['我', 'Yes, please. Small chunks are fine.', '对，切成小块就行。'],
        ['朋友', 'Do we need to peel them?', '需要去皮吗？'],
        ['我', 'No, just remove the stems.', '不用，把蒂去掉就好。'],
        ['朋友', "Okay. I'll put them in this bowl when they're ready.", '好，切好后我放进这个碗。'],
      ]],
      ['准备下一步', '区分切片、暂放和另备食材', [
        ['朋友', 'The tomatoes are ready. What should I do next?', '番茄准备好了，接下来做什么？'],
        ['我', 'Could you slice the onion thinly?', '你能把洋葱切成薄片吗？'],
        ['朋友', 'Sure. Are we using the chicken today?', '可以，今天用鸡肉吗？'],
        ['我', "No, it's still frozen. Let's let it thaw in the fridge for tomorrow.", '不用，还冻着。放冰箱里解冻，明天再用。'],
        ['朋友', 'Got it. Where should I put the onion?', '明白，洋葱放哪里？'],
        ['我', 'Set it aside in that small bowl, please.', '先放在那个小碗里备用。'],
      ]],
    ],
    branches: [
      ['切法没说清', '补问具体要求', [
        ['朋友', 'Should I slice the carrots or chop them into chunks?', '胡萝卜切片还是切块？'],
        ['我', 'Thin slices, please. They cook more quickly.', '切薄片吧，熟得快一些。'],
        ['朋友', 'Like this?', '这样吗？'],
        ['我', "Yes, that's just right.", '对，这样正好。'],
      ]],
      ['准备生肉时发现混用砧板', '说明具体处理动作', [
        ['我', 'Has this board been used for raw chicken?', '这块砧板切过生鸡肉吗？'],
        ['朋友', "Yes, it has. I'll wash it properly.", '切过，我会把它彻底洗干净。'],
        ['我', "Thanks. Let's use the other board for the vegetables.", '谢谢，蔬菜先用另一块砧板吧。'],
        ['朋友', "Okay. I'll wash my hands before I start.", '好，我开始前先洗手。'],
      ]],
    ],
    practice: { substitutions: ['把 tomatoes 换成 cucumbers，请求洗黄瓜。', '把 thin slices 换成 small chunks，改变切法。', '把 rinse the rice 换成 beat the eggs，说明自己打鸡蛋。'], responses: [['How small should I cut these?', '让对方切成小块。', 'Small chunks are fine.'], ['Where should I put this?', '放小碗里备用。', 'Set it aside in the small bowl, please.'], ['What should I do next?', '请对方洗蔬菜。', 'Could you wash the vegetables?']], task: '分配两项备菜任务，说清切法和放置位置；遇到食材仍冻结时重新安排菜单。' },
  }),
  D08: defineLesson('D08', {
    scenario: '和朋友做番茄意面。你煮面，朋友做酱汁；需要递工具、调火和尝味道，发现没有罗勒时协商替代。',
    phrases: ['turn the heat down 把火调小', 'give it a stir 搅拌一下', 'keep an eye on it 留意一下', 'stick to the bottom 粘锅底', 'a pinch of salt 一小撮盐', 'do the washing-up 洗碗'],
    core: [
      ["I'll cook the pasta. Could you make the sauce?", '我来煮意面，你能做酱汁吗？', '我'],
      ['Could you pass me the wooden spoon?', '能把木勺递给我吗？', '朋友'],
      ['Could you turn the heat down a little?', '能把火调小一点吗？', '我'],
      ["Give it a stir so it doesn't stick.", '搅拌一下，免得粘锅。', '我'],
      ['Could you keep an eye on the sauce?', '你能留意一下酱汁吗？', '我', 'keep an eye on 指照看或留意，不是一直盯着不动。'],
      ['Does it need more salt?', '需要再加点盐吗？', '朋友'],
      ['Just a pinch should do.', '一小撮应该就够了。', '我', 'should do 在这里是估计这样就够，不是说某人有义务做事。'],
      ["We're out of basil.", '我们没有罗勒了。', '朋友'],
      ['Can we use parsley instead?', '我们可以改用欧芹吗？', '我'],
      ["Let's taste it before we add any more.", '再加之前先尝尝吧。', '我'],
      ["I'll clear the table.", '我来收拾桌子。', '我'],
      ["I'll do the washing-up.", '我来洗碗。', '朋友', 'do the dishes 也很自然，尤其常见于美式英语。'],
    ],
    dialogues: [
      ['一起把饭做好', '分工，递工具和调火', [
        ['我', "I'll cook the pasta. Could you make the sauce?", '我煮意面，你能做酱汁吗？'],
        ['朋友', 'Sure. Could you pass me the wooden spoon?', '可以，能把木勺递给我吗？'],
        ['我', "Here you go. The sauce is bubbling quite a lot.", '给你，酱汁冒泡挺厉害的。'],
        ['朋友', 'Should I turn the heat down?', '要把火调小吗？'],
        ['我', 'Yes, a little. Give it a stir as well.', '对，调小一点，也搅拌一下。'],
        ['朋友', "Okay. I'll keep an eye on it while you drain the pasta.", '好，你给意面沥水时我来照看。'],
      ]],
      ['尝味道并收尾', '小量调整，商量收拾', [
        ['朋友', 'Does the sauce need more salt?', '酱汁还需要加盐吗？'],
        ['我', "Let's taste it first.", '先尝尝吧。'],
        ['朋友', 'I think a little more would help.', '我觉得再加一点会好些。'],
        ['我', 'Just a pinch should do. Then we can serve it.', '一小撮应该就够，然后就可以上桌了。'],
        ['朋友', "Sounds good. I'll do the washing-up after dinner.", '好，晚饭后我洗碗。'],
        ['我', "Thanks. I'll clear the table.", '谢谢，我收拾桌子。'],
      ]],
    ],
    branches: [
      ['少一种配料', '协商替代而不临时停下', [
        ['朋友', "We're out of basil.", '没有罗勒了。'],
        ['我', 'Can we use parsley instead?', '能改用欧芹吗？'],
        ['朋友', "Yes, we have some in the fridge.", '能，冰箱里有一些。'],
        ['我', "Great. Let's use a little of that.", '好，那就用一点欧芹。'],
      ]],
      ['酱汁快粘锅了', '及时提醒并说明下一步', [
        ['朋友', 'The sauce is starting to stick to the bottom.', '酱汁开始粘锅底了。'],
        ['我', 'Turn the heat down and give it a stir, please.', '把火调小，再搅拌一下。'],
        ['朋友', 'Should I add a little water?', '要加点水吗？'],
        ['我', "Yes, just a little. Let's check it again in a minute.", '要，加一点就好。一分钟后再看看。'],
      ]],
    ],
    practice: { substitutions: ['把 sauce 换成 soup，请朋友留意汤。', '把 wooden spoon 换成 spatula，请对方递锅铲。', '把 clear the table 换成 wipe the counter，分配擦台面的任务。'], responses: [['Does it need more salt?', '先尝后决定。', "Let's taste it first."], ["We're out of basil.", '建议换欧芹。', 'Could we use parsley instead?'], ["I'll wash the dishes.", '接下收拾桌子的任务。', "Thanks. I'll clear the table."]], task: '与朋友分工做饭，完成递工具、调火和尝味道；缺一种配料时提出替代，最后分配收拾任务。' },
  }),
  D09: defineLesson('D09', {
    scenario: '周末在家洗衣和整理房间。衣服正在洗，床单要另开一轮；确认衣物标签后选择晾干，安排吸尘和倒垃圾。',
    phrases: ['a load of laundry 一轮待洗衣物', 'hang it up to dry 挂起来晾干', 'still damp 还有点潮', 'fold the clothes 叠衣服', 'take out the trash 倒垃圾', 'vacuum the floor 吸尘'],
    core: [
      ["I'll put a load of laundry on.", '我开一轮洗衣。', '我', 'a load 指洗衣机一次处理的衣物；也可以说 I’ll start a load of laundry。'],
      ['Can these go in the washing machine?', '这些可以机洗吗？', '我'],
      ["Let's check the care labels.", '看看洗护标签吧。', '家人'],
      ["I'll hang these up to dry.", '我把这些挂起来晾干。', '我'],
      ["They're still a little damp.", '它们还有点潮。', '家人', 'damp 通常指微湿；soaking wet 是湿透了，程度不同。'],
      ['Could you help me fold the clothes?', '你能帮我叠衣服吗？', '我'],
      ["I'll take out the trash.", '我来倒垃圾。', '我'],
      ['Could you vacuum the living room?', '你能给客厅吸尘吗？', '我'],
      ["I've already wiped the counter.", '我已经擦过台面了。', '家人', 'already 配合完成时，说明这件事已经做过，避免重复分工。'],
      ["I haven't changed the sheets yet.", '我还没换床单。', '我'],
      ["Let's do one thing at a time.", '我们一件一件来吧。', '我'],
      ["I'll finish the rest after lunch.", '剩下的我午饭后做完。', '我'],
    ],
    dialogues: [
      ['安排家务', '说明已做事项，避免重复', [
        ['我', "I'll put a load of laundry on. Could you vacuum the living room?", '我先洗一轮衣服，你能给客厅吸尘吗？'],
        ['家人', "Sure. I've already wiped the kitchen counter.", '可以，我已经擦过厨房台面了。'],
        ['我', "Thanks. I'll take out the trash while the machine is running.", '谢谢，洗衣机运行的时候我去倒垃圾。'],
        ['家人', 'Have you changed the sheets yet?', '你换床单了吗？'],
        ['我', "Not yet. I'll wash them in the next load.", '还没，下一轮再洗。'],
        ['家人', "Okay. I'll help you put the clean ones on later.", '好，待会我帮你铺干净的。'],
      ]],
      ['检查是否晾干', '说明状态，安排后续', [
        ['我', 'Are the clothes dry yet?', '衣服干了吗？'],
        ['家人', "The towels are dry, but the shirts are still a little damp.", '毛巾干了，但衬衫还有点潮。'],
        ['我', "Let's leave the shirts up for a bit longer.", '衬衫再晾一会儿吧。'],
        ['家人', 'Could you help me fold the towels?', '能帮我叠毛巾吗？'],
        ['我', "Sure. I'll put them in the cupboard afterward.", '可以，叠好后我放进柜子。'],
        ['家人', "Thanks. I'll check the shirts again after lunch.", '谢谢，午饭后我再看看衬衫。'],
      ]],
    ],
    branches: [
      ['衣物不能机洗', '依据标签调整安排', [
        ['我', 'Can this sweater go in the machine?', '这件毛衣能机洗吗？'],
        ['家人', 'The label says hand wash only.', '标签写着只能手洗。'],
        ['我', "Okay. I'll keep it out of this load.", '好，这一轮不洗它。'],
        ['家人', "Let's follow the instructions on the label.", '按标签上的说明洗吧。'],
      ]],
      ['今天来不及做完', '说清可完成的部分', [
        ['我', "I don't think I can finish everything this morning.", '今天上午我可能没法全做完。'],
        ['家人', 'What can you get done before lunch?', '午饭前能做完哪些？'],
        ['我', 'The laundry and the trash. I can change the sheets later.', '洗衣和倒垃圾，床单可以晚点换。'],
        ['家人', "That works. I'll handle the floors.", '可以，地板我来处理。'],
      ]],
    ],
    practice: { substitutions: ['把 living room 换成 bedroom，请求给卧室吸尘。', '把 shirts 换成 towels，描述毛巾仍潮湿。', '把 after lunch 换成 this evening，安排剩余家务。'], responses: [['Have you changed the sheets?', '还没，晚饭后换。', "Not yet. I'll do it after dinner."], ['Can this go in the machine?', '建议先看标签。', "Let's check the care label."], ['Could you fold these?', '答应并说明放置位置。', "Sure. I'll put them in the cupboard afterward."]], task: '商量三项家务，说明已完成和未完成的事，遇到没晾干的衣服时安排下一步。' },
  }),
  D10: defineLesson('D10', {
    scenario: '你和朋友正在你家整理东西，晚上要去朋友家。练习桌边递物、把东西带到说话者所在处，以及离开时带走物品。',
    phrases: ['bring it over 带到这里', 'take it with you 随身带走', 'pass it to me 递给我', 'pick it up 拿起或取回', 'put it away 收起来', 'leave it here 留在这里'],
    core: [
      ['Could you pass me the charger?', '能把充电器递给我吗？', '我'],
      ["I'll bring it over to you.", '我把它拿到你那边。', '朋友', 'bring 可以以听话者所在处为视角，不只等于朝说话者移动。'],
      ["Don't forget to take your umbrella with you.", '别忘了把你的伞带走。', '我'],
      ['Could you put these books away?', '能把这些书收起来吗？', '我'],
      ['Where do they go?', '它们放哪里？', '朋友'],
      ['They go on the top shelf.', '放在最上层架子上。', '我'],
      ['Can you hold this for a second?', '能帮我拿一下这个吗？', '我'],
      ['Could you pick up the keys from the floor?', '能把地上的钥匙捡起来吗？', '我', 'pick up 在这里是拿起；其他语境也可以是取件、接人或购买。'],
      ["I'll take this bag upstairs.", '我把这个包拿到楼上去。', '朋友'],
      ['Should I leave it here?', '我把它留在这里吗？', '朋友'],
      ['Could you bring the book to my place tonight?', '今晚你能把书带到我家吗？', '朋友'],
      ["I'll drop it off on my way home.", '我回家的路上顺便送过去。', '我', 'drop off 强调送到后放下或交给对方，不一定停留很久。'],
    ],
    dialogues: [
      ['桌边递物和整理', '用具体位置消除歧义', [
        ['我', 'Could you pass me the charger next to you?', '能把你旁边的充电器递给我吗？'],
        ['朋友', 'This white one?', '这个白色的吗？'],
        ['我', 'Yes, thanks. Could you put these books away too?', '对，谢谢，也能把这些书收起来吗？'],
        ['朋友', 'Sure. Where do they go?', '可以，放哪里？'],
        ['我', 'On the top shelf, next to the dictionary.', '最上层，词典旁边。'],
        ['朋友', "Got it. I'll put them there.", '明白，我放在那里。'],
      ]],
      ['出门前说清带到哪里', '同一物品，变化目的地视角', [
        ['朋友', 'Could you bring my book to my place tonight?', '今晚你能把我的书带到我家吗？'],
        ['我', "Sure. I'll drop it off on my way home.", '可以，我回家的路上顺便送过去。'],
        ['朋友', "Thanks. I'll leave now.", '谢谢，那我先走了。'],
        ['我', "Don't forget to take your umbrella with you.", '别忘了带走你的伞。'],
        ['朋友', 'Oh, right. Can you hold my bag for a second?', '哦，对了，能帮我拿一下包吗？'],
        ['我', 'Of course. Your umbrella is by the door.', '当然，你的伞在门边。'],
      ]],
    ],
    branches: [
      ['拿错了东西', '指明特征并纠正', [
        ['朋友', 'Here is the cable you wanted.', '这是你要的数据线。'],
        ['我', 'Thanks, but I meant the longer black one.', '谢谢，不过我说的是那根更长的黑色线。'],
        ['朋友', 'The one by the laptop?', '笔记本电脑旁边那根吗？'],
        ['我', "Yes, that's the one.", '对，就是那根。'],
      ]],
      ['目的地听错', '说明移动方向', [
        ['朋友', 'Should I take the box downstairs?', '要把箱子拿到楼下吗？'],
        ['我', "No, bring it up here, please. I'm in the bedroom.", '不用，请拿到楼上我这里，我在卧室。'],
        ['朋友', 'Okay, upstairs to the bedroom.', '好，拿到楼上卧室。'],
        ['我', 'Exactly. Thanks for checking.', '没错，谢谢你确认。'],
      ]],
    ],
    practice: { substitutions: ['把 charger 换成 remote，请递遥控器。', '说话者在楼下，请对方 bring the box downstairs to me。', '对方即将出门，提醒 take your keys with you。'], responses: [['Where do these go?', '放最上层。', 'They go on the top shelf.'], ['This white one?', '要黑色的。', 'No, the black one, please.'], ['Should I leave it here?', '请放门边。', 'Yes, by the door, please.']], task: '给出三项拿取或整理请求，每次都说清物品和位置；朋友听错一次后补充说明。' },
  }),
  D11: defineLesson('D11', {
    scenario: '快递员来电时你不在家。门边允许放置普通包裹，但需签收的包裹改约时间；另练习收到破损包裹时联系卖家。',
    phrases: ['a delivery 配送或送来的东西', 'leave it by the door 放在门边', 'sign for it 签收', 'reschedule the delivery 改约配送', 'damaged packaging 破损包装', 'the tracking number 物流单号'],
    core: [
      ['Is there a package for me?', '有我的包裹吗？', '收件人'],
      ["I'm not home at the moment.", '我现在不在家。', '收件人'],
      ['Could you leave it by the door?', '能把它放在门边吗？', '收件人', '只用于允许放置且你接受该位置的场景；有些包裹必须当面签收。'],
      ['Do I need to sign for it?', '我需要签收吗？', '收件人', 'sign for a package 是签收包裹；不是简单签一个任意文件。'],
      ["I'll be back after six.", '我六点以后回来。', '收件人'],
      ['Could we arrange another delivery time?', '能另约一个配送时间吗？', '收件人'],
      ['What is the tracking number?', '物流单号是什么？', '客服'],
      ['The box arrived damaged.', '箱子送到时已经破损了。', '收件人', '说明到达时的状态；没有核查前，不推断是谁造成破损。'],
      ["I haven't opened it yet.", '我还没打开。', '收件人'],
      ['One of the items is missing.', '里面少了一件东西。', '收件人'],
      ['Could you send us a photo?', '能给我们发张照片吗？', '客服'],
      ['What should I do next?', '我接下来应该怎么做？', '收件人'],
    ],
    dialogues: [
      ['说明放置位置', '确认无需签收后安排', [
        ['快递员', 'Hi, I have a package for you. Are you home?', '你好，有你的包裹，你在家吗？'],
        ['收件人', "I'm not home at the moment. Do I need to sign for it?", '我现在不在家，需要签收吗？'],
        ['快递员', 'No signature is required for this one.', '这个不需要签字。'],
        ['收件人', 'Could you leave it by the door, behind the plant pot?', '能放门边的花盆后面吗？'],
        ['快递员', "Sure. I'll put it there and mark it as delivered.", '可以，我放在那里并标记已送达。'],
        ['收件人', 'Thanks for letting me know.', '谢谢你通知我。'],
      ]],
      ['向卖家说明破损', '描述事实并询问处理', [
        ['收件人', 'Hi, the box from my order arrived damaged.', '你好，我订单的箱子送到时破损了。'],
        ['客服', 'Sorry to hear that. Is the item damaged too?', '很抱歉，里面的商品也坏了吗？'],
        ['收件人', "I haven't opened it yet. What should I do next?", '我还没打开，下一步该怎么做？'],
        ['客服', 'Could you send us a photo of the packaging and your order number?', '能发包装照片和订单号给我们吗？'],
        ['收件人', 'Of course. Should I keep the box?', '可以，我需要保留箱子吗？'],
        ['客服', 'Yes, please keep it while we review the issue.', '需要，在我们核实期间请保留。'],
      ]],
    ],
    branches: [
      ['必须当面签收', '协商可行时间', [
        ['快递员', 'This package requires a signature.', '这个包裹需要签字。'],
        ['收件人', "I'll be back after six. Can we arrange another delivery time?", '我六点以后回来，能另约时间吗？'],
        ['快递员', 'We can try again tomorrow morning.', '我们可以明天上午再送一次。'],
        ['收件人', "That works. I'll be home then.", '可以，那个时候我会在家。'],
      ]],
      ['显示送达却没找到', '报告状态而不先认定丢失', [
        ['收件人', "The tracking says delivered, but I can't find the package.", '物流显示已送达，但我找不到包裹。'],
        ['客服', 'Have you checked the delivery photo?', '你查看配送照片了吗？'],
        ['收件人', 'Yes. The door in the photo is not mine.', '看了，照片里的门不是我家的。'],
        ['客服', "Please send us the tracking number. We'll look into it.", '请把物流单号发给我们，我们会调查。'],
      ]],
    ],
    practice: { substitutions: ['把 after six 换成 before noon，说明在家时间。', '把 behind the plant pot 换成 inside the porch，说明门廊内位置。', '把 damaged 换成 wet，描述包装湿了。'], responses: [['Are you home?', '不在，问是否需签收。', "Not right now. Do I need to sign for it?"], ['Could you send a photo?', '答应，并询问是否保留包装。', 'Sure. Should I keep the packaging?'], ['We can deliver tomorrow morning.', '答应并确认在家。', "That works. I'll be home."]], task: '说明自己不在家，确认签收条件并安排送达；随后用两句事实说明破损或找不到包裹。' },
  }),
  D12: defineLesson('D12', {
    scenario: '在朋友家手机电量只剩百分之五，想借 USB-C 充电器。确认插座、接口和归还时间，发现没有充电提示时逐步排查。',
    phrases: ['about to die 快没电', 'a power outlet 电源插座', 'plug it in 插上电源', 'a USB-C cable USB-C 线', 'a power bank 充电宝', 'give it back 归还'],
    core: [
      ["My phone's about to die.", '我的手机快没电了。', '我', '这里的 die 是设备快耗尽电量，不是设备已经坏了。'],
      ['Could I borrow your charger?', '我能借一下你的充电器吗？', '我', 'borrow 是从别人那里借来；lend 是把自己的东西借给别人。'],
      ['What kind of cable do you need?', '你需要哪种线？', '朋友'],
      ['A USB-C cable, please.', 'USB-C 线，谢谢。', '我'],
      ['Is there an outlet nearby?', '附近有插座吗？', '我'],
      ['Can I plug it in here?', '我可以在这里插上充电吗？', '我'],
      ["It doesn't seem to be charging.", '好像没有在充电。', '我', 'doesn’t seem to 表达观察到的现象，给进一步检查留余地。'],
      ['Try the other outlet.', '试试另一个插座。', '朋友'],
      ['Do you have a power bank I could use?', '你有我可以借用的充电宝吗？', '我'],
      ["I'll give it back before I leave.", '我走之前会还给你。', '我'],
      ['How much battery do you have left?', '你还剩多少电？', '朋友'],
      ['Only five percent.', '只剩百分之五。', '我'],
    ],
    dialogues: [
      ['借充电器', '确认接口和归还时间', [
        ['我', "My phone's about to die. Could I borrow your charger?", '我的手机快没电了，能借一下你的充电器吗？'],
        ['朋友', 'Sure. What kind of cable do you need?', '可以，你需要哪种线？'],
        ['我', 'A USB-C cable. I only have five percent left.', 'USB-C 线，我只剩百分之五的电。'],
        ['朋友', "Here's one. There's an outlet by the sofa.", '这有一根，沙发旁边有插座。'],
        ['我', "Thanks. I'll give it back before I leave.", '谢谢，我走之前还给你。'],
        ['朋友', 'No problem. Leave it charging for a while.', '没问题，先充一会儿吧。'],
      ]],
      ['充电没反应', '报告现象并检查连接', [
        ['我', "It doesn't seem to be charging.", '好像没在充电。'],
        ['朋友', 'Is the cable plugged in properly?', '线插好了吗？'],
        ['我', 'I think so. Can I try the other outlet?', '应该插好了，我能试另一个插座吗？'],
        ['朋友', 'Sure, use the one by the desk.', '可以，用书桌旁边那个。'],
        ['我', "It's charging now. Thanks for your help.", '现在充上了，谢谢你帮忙。'],
        ['朋友', 'Great. Let me know if it stops again.', '好，要是又停了告诉我。'],
      ]],
    ],
    branches: [
      ['接口不匹配', '明确型号而不只说不能用', [
        ['我', "This cable doesn't fit my phone.", '这根线插不了我的手机。'],
        ['朋友', 'Oh, do you need USB-C?', '哦，你需要 USB-C 吗？'],
        ['我', 'Yes. Do you have one?', '对，你有吗？'],
        ['朋友', "Yes, there's one in the drawer.", '有，抽屉里有一根。'],
      ]],
      ['外出无法插电', '询问充电宝', [
        ['我', "There isn't an outlet here, and my battery is low.", '这里没有插座，而且我的电量很低。'],
        ['朋友', 'You can use my power bank.', '你可以用我的充电宝。'],
        ['我', 'Thanks. Could I keep it until we get home?', '谢谢，我能借到我们到家吗？'],
        ['朋友', "Sure. Just give it back tonight.", '可以，今晚还给我就好。'],
      ]],
    ],
    practice: { substitutions: ['把 five percent 换成 ten percent，描述剩余电量。', '把 charger 换成 power bank，请借充电宝。', '把 before I leave 换成 tomorrow morning，商量归还时间。'], responses: [['What kind of cable do you need?', '需要 USB-C。', 'A USB-C cable, please.'], ['Can you give it back tonight?', '答应并感谢。', 'Of course. Thanks for lending it to me.'], ['Is it charging now?', '已经充上了。', "Yes, it's charging now."]], task: '借一个匹配的充电器，确认插座和归还时间；无法充电时说明现象并试另一个连接。' },
  }),
};
