import { defineLesson } from './lesson-format.js';

export const outingLessons = {
  D13: defineLesson('D13', {
    scenario: '虚构地铁网络：从当前车站去机场，先坐开往 Central 的列车，再在 Central 换乘蓝线。正常方案在二号站台候车；变化分支分别练习坐反和停运。',
    phrases: ['the right platform 正确的站台', 'change at Central 在 Central 换乘', 'get off 下车', 'the opposite direction 相反方向', 'a direct train 直达列车', 'a service disruption 运行中断'],
    core: [
      ['Is this the right platform for the airport?', '去机场是在这个站台吗？', '乘客'],
      ['Which line should I take?', '我应该坐哪条线？', '乘客'],
      ['You need to change at Central.', '你需要在 Central 换乘。', '工作人员', 'change 在这里是换乘；也可说 transfer，实际指示牌措辞可能不同。'],
      ['So I change at Central, right?', '所以我在 Central 换乘，对吗？', '乘客', '复述关键地点，避免只说 Okay 却没确认路线。'],
      ['Does this train stop at Central?', '这班列车停 Central 吗？', '乘客'],
      ['How many stops is it from here?', '从这里过去有几站？', '乘客'],
      ['Get off at the next stop.', '下一站下车。', '工作人员'],
      ["I think I'm going the wrong way.", '我好像坐反方向了。', '乘客'],
      ['Where is the platform for the other direction?', '另一方向的站台在哪里？', '乘客'],
      ['Is there a direct train to the airport?', '有直达机场的列车吗？', '乘客'],
      ['Sorry, which platform did you say?', '不好意思，你刚才说几号站台？', '乘客', '只补问站台编号；若路线也没听懂，可以请对方重新说明路线。'],
      ['Follow the signs for the blue line.', '沿着蓝线的指示牌走。', '工作人员'],
    ],
    dialogues: [
      ['问清乘车路线', '先确认站台，再复述换乘', [
        ['乘客', 'Is this the right platform for the airport?', '去机场是在这个站台吗？'],
        ['工作人员', 'Yes. Take the train to Central, then change to the blue line.', '对，坐到 Central，再换蓝线。'],
        ['乘客', 'So I change at Central, right?', '所以在 Central 换乘，对吗？'],
        ['工作人员', "That's right. Follow the airport signs when you get there.", '没错，到那里后沿机场指示牌走。'],
        ['乘客', 'How many stops is Central from here?', '从这里到 Central 有几站？'],
        ['工作人员', "Three stops. It's announced on the train too.", '三站，车上也会报站。'],
      ]],
      ['只补问没听清的信息', '有针对性地确认', [
        ['乘客', 'Does this train stop at Central?', '这班车停 Central 吗？'],
        ['工作人员', 'No, you need platform two.', '不停，你需要去二号站台。'],
        ['乘客', 'Sorry, which platform did you say?', '不好意思，你刚说几号站台？'],
        ['工作人员', 'Platform two, across the footbridge.', '二号站台，走过人行桥就是。'],
        ['乘客', 'Thanks. Is that the train toward Central?', '谢谢，那是开往 Central 的列车吗？'],
        ['工作人员', 'Yes. Check the display before you board.', '是的，上车前看一下显示屏。'],
      ]],
    ],
    branches: [
      ['坐反方向', '先安全下车，再找反向站台', [
        ['乘客', "I think I'm going the wrong way. Is Central ahead?", '我好像坐反了，前面是 Central 吗？'],
        ['乘客乙', "No, we're heading away from Central.", '不是，我们正往离开 Central 的方向走。'],
        ['乘客', 'Should I get off at the next stop?', '我应该下一站下车吗？'],
        ['乘客乙', 'Yes, then follow the signs for trains toward Central.', '对，然后按开往 Central 的指示牌走。'],
      ]],
      ['蓝线临时停运', '重新询问可行路线', [
        ['工作人员', 'The blue line is closed at the moment.', '蓝线目前停运。'],
        ['乘客', 'What is the best way to get to the airport now?', '现在去机场怎么走最合适？'],
        ['工作人员', 'There is a replacement bus outside exit three.', '三号出口外有接驳巴士。'],
        ['乘客', 'Exit three, for the replacement bus. Got it, thanks.', '三号出口，坐接驳巴士，明白了，谢谢。'],
      ]],
    ],
    practice: { substitutions: ['把 airport 换成 city center，询问是否找对站台。', '把 platform two 换成 platform four，补问没听清的编号。', '把 Central 换成 River Park，复述换乘站。'], responses: [['You need to change at Central.', '复述换乘站。', 'So I change at Central, right?'], ['The blue line is closed.', '询问替代路线。', 'How can I get to the airport now?'], ['Take the train from platform two.', '只确认编号。', 'Platform two, right?']], task: '从陌生车站去机场，问清方向和换乘；只针对漏听的信息补问，再应对一次路线变化。' },
  }),
  D14: defineLesson('D14', {
    scenario: '虚构城市提供单程票和仅覆盖市区的日票，机场线路另计。你先比较票种，再处理卡片余额不足导致的闸机失败。',
    phrases: ['a single ticket 单程票', 'a day pass 日票', 'cover this journey 覆盖这段行程', 'top up the card 给卡充值', 'tap the card 刷感应卡', 'insufficient balance 余额不足'],
    core: [
      ['Could I get a single ticket to Central?', '能给我一张去 Central 的单程票吗？', '乘客'],
      ['How much is a day pass?', '日票多少钱？', '乘客'],
      ['Does it cover the airport line?', '它包含机场线路吗？', '乘客', '票种覆盖范围依当地规定，需要问清，不把练习设定当真实规则。'],
      ['You need a separate ticket for that.', '那个需要另买一张票。', '工作人员'],
      ['Can I use this on the bus as well?', '这个也能坐公交吗？', '乘客'],
      ['Where can I top up my card?', '哪里可以给卡充值？', '乘客', 'top up 常指补充余额；add money to my card 也很清楚自然。'],
      ["My card isn't working at the gate.", '我的卡在闸机这里刷不了。', '乘客'],
      ['Could you check the balance for me?', '能帮我查一下余额吗？', '乘客'],
      ['The balance is too low.', '余额不足。', '工作人员'],
      ['How much do I need to add?', '我需要充多少钱？', '乘客'],
      ['Try tapping it again.', '试着再刷一次。', '工作人员', 'tap 通常是贴近感应区刷卡；磁条卡划过读卡器通常用 swipe。'],
      ["It's working now, thanks.", '现在能用了，谢谢。', '乘客'],
    ],
    dialogues: [
      ['选择票种', '结合今天的实际行程', [
        ['乘客', "I'm making three trips in the city today. How much is a day pass?", '我今天要在市区坐三次车，日票多少钱？'],
        ['工作人员', 'Eight dollars. It covers city trains and buses.', '八美元，包含市区列车和公交。'],
        ['乘客', 'Does it cover the airport line?', '包含机场线路吗？'],
        ['工作人员', 'No, you need a separate ticket for that.', '不包含，机场线路要另买票。'],
        ['乘客', "I'm staying in the city today, so I'll get the day pass.", '我今天只在市区，所以买日票。'],
        ['工作人员', 'Sure. Here you are.', '好，给你。'],
      ]],
      ['处理余额不足', '说明失败位置并确认充值', [
        ['乘客', "My card isn't working at the gate. Could you check the balance?", '我的卡在闸机刷不了，能查一下余额吗？'],
        ['工作人员', 'The balance is too low for this trip.', '余额不够支付这段行程。'],
        ['乘客', 'How much do I need to add?', '需要充多少钱？'],
        ['工作人员', 'At least three dollars for this journey. You can use that machine.', '这段行程至少再充三美元，可以用那台机器。'],
        ['乘客', "I've topped it up. Should I try the gate again?", '我充好了，要再试一次闸机吗？'],
        ['工作人员', 'Yes. Tap it once and wait for the green light.', '对，刷一次，等绿灯亮起。'],
      ]],
    ],
    branches: [
      ['机器没有出票', '保留付款信息并求助', [
        ['乘客', "The machine took my payment, but it didn't print a ticket.", '机器收了款，但没有打印票。'],
        ['工作人员', 'Which machine did you use?', '你用的是哪台机器？'],
        ['乘客', 'The one by the entrance. I have the payment confirmation.', '入口旁边那台，我有付款确认记录。'],
        ['工作人员', "Please show me the confirmation, and I'll check it.", '请给我看确认记录，我核查一下。'],
      ]],
      ['日票不适用于当前线路', '明确补票需求', [
        ['乘客', 'Why is my day pass not accepted here?', '为什么这里不能用我的日票？'],
        ['工作人员', 'This is the airport line, which is not included.', '这是机场线路，不在日票范围内。'],
        ['乘客', 'Where can I buy the right ticket?', '哪里能买适用的票？'],
        ['工作人员', 'At the ticket counter on your left.', '在你左边的售票柜台。'],
      ]],
    ],
    practice: { substitutions: ['把 single ticket 换成 day pass，询问购买。', '把 airport line 换成 night buses，确认是否覆盖夜班公交。', '把 balance 换成 ticket，询问工作人员能否检查车票。'], responses: [['The balance is too low.', '询问需充值多少。', 'How much do I need to add?'], ['It does not cover the airport line.', '问哪里买适用票。', 'Where can I buy the right ticket?'], ['Try tapping it again.', '说明已经可以使用。', "It's working now, thanks."]], task: '根据行程选择票种，核实范围；闸机失败时说明问题，并问清解决办法。' },
  }),
  D15: defineLesson('D15', {
    scenario: '想用共享单车骑到公园，先扫码但解锁失败；换车后检查刹车，结束行程时确认停车区和 App 状态。具体停车和收费规则以服务方说明为准。',
    phrases: ['scan the code 扫码', 'unlock the bike 解锁车', 'check the brakes 检查刹车', 'a designated parking area 指定停车区', 'end the ride 结束行程', 'an extra charge 额外收费'],
    core: [
      ["I can't get the bike to unlock.", '这辆车我解锁不了。', '用户', 'get something to do 表示让某物产生结果；本句强调尝试后仍打不开。'],
      ['Have you scanned the code?', '你扫码了吗？', '朋友'],
      ['The app says the bike is unavailable.', 'App 显示这辆车不可用。', '用户'],
      ["Let's try another one.", '我们换一辆试试吧。', '朋友'],
      ["The brakes don't feel right.", '刹车感觉不太对。', '用户'],
      ["I don't feel safe riding this.", '骑这辆车我感觉不安全。', '用户'],
      ['Where am I allowed to park it?', '我可以把它停在哪里？', '用户'],
      ['Do I need to park in the marked area?', '需要停在标记区域里吗？', '用户'],
      ['How do I end the ride?', '怎么结束行程？', '用户'],
      ["The app still says the ride is in progress.", 'App 还显示行程进行中。', '用户', 'in progress 指尚未结束；描述屏幕状态时 says 也很自然。'],
      ["I've been charged twice for the same ride.", '同一次行程扣了我两次钱。', '用户', '被动形式说明自己被收费；先核对是两笔已入账收费还是待处理记录。'],
      ['Could you check this charge?', '能帮我核查这笔收费吗？', '用户'],
    ],
    dialogues: [
      ['解锁前后检查', '识别不可用车辆', [
        ['用户', "I can't get this bike to unlock.", '这辆单车解锁不了。'],
        ['朋友', 'Have you scanned the code?', '你扫码了吗？'],
        ['用户', 'Yes, but the app says the bike is unavailable.', '扫了，但 App 说车不可用。'],
        ['朋友', "Let's try another one. Check the brakes before we leave.", '换一辆吧，出发前检查刹车。'],
        ['用户', 'This one has unlocked, and the brakes feel fine.', '这辆解锁了，刹车也正常。'],
        ['朋友', 'Great. We can take the cycle path to the park.', '好，可以沿自行车道去公园。'],
      ]],
      ['结束行程', '确认停放和系统状态', [
        ['用户', 'Are we allowed to park the bikes here?', '我们能把车停这里吗？'],
        ['朋友', 'The app shows a designated parking area just ahead.', 'App 显示前面有指定停车区。'],
        ['用户', "Let's park there. How do I end the ride?", '停那里吧，怎么结束行程？'],
        ['朋友', 'Follow the instructions in the app and check for confirmation.', '按 App 里的说明操作，再看是否有确认。'],
        ['用户', 'It says the ride has ended now.', '现在显示行程已结束。'],
        ['朋友', 'Great. Check the charge as well.', '好，也核对一下费用。'],
      ]],
    ],
    branches: [
      ['刹车异常', '停止使用并报告', [
        ['用户', "The brakes don't feel right. I don't feel safe riding this.", '刹车感觉不对，骑这个我感觉不安全。'],
        ['朋友', "Don't ride it. Let's report it in the app.", '别骑，先在 App 里报告。'],
        ['用户', "Okay. I'll mark it as faulty and find another bike.", '好，我标记故障，再找另一辆。'],
        ['朋友', 'Check that the first rental has ended too.', '也检查第一笔租车是否已经结束。'],
      ]],
      ['行程结束仍被收费', '提供行程记录', [
        ['用户', 'I ended the ride at three, but the app kept charging me.', '我三点结束了行程，但 App 继续收费。'],
        ['客服', 'Could you send us the ride ID and a screenshot?', '能发一下行程编号和截图吗？'],
        ['用户', 'Yes. Could you check the extra charge?', '能，请核查额外收费。'],
        ['客服', "We'll review the record and get back to you.", '我们会核查记录后回复你。'],
      ]],
    ],
    practice: { substitutions: ['把 unavailable 换成 already in use，说明已被使用。', '把 brakes 换成 seat，说明车座不稳。', '把 at three 换成 at four thirty，说明还车时间。'], responses: [['Have you scanned the code?', '扫过但打不开。', "Yes, but it won't unlock."], ['The brakes are faulty.', '决定不骑并报告。', "I won't ride it. I'll report it in the app."], ['Could you send the ride ID?', '答应并说明还有截图。', 'Sure. I have a screenshot too.']], task: '完成解锁、检查、停车和结束行程；遇到故障就停止使用，收费异常时提供可核查的信息。' },
  }),
  D16: defineLesson('D16', {
    scenario: '约朋友下午两点去公园散步。出门前看着要下雨，到了公园后雨变大；商量改去附近咖啡馆或改到明天。',
    phrases: ['go for a walk 去散步', 'a light drizzle 毛毛雨', 'pouring 雨下得很大', 'clear up 天气放晴', 'take shelter 避雨', 'make other plans 改作别的安排'],
    core: [
      ['Do you feel like going for a walk?', '你想去散步吗？', '我'],
      ["Let's meet at the park entrance.", '我们在公园入口见吧。', '我'],
      ["Looks like it's about to rain.", '看样子快要下雨了。', '我'],
      ["It's only a light drizzle.", '只是毛毛雨。', '朋友'],
      ["It's pouring now.", '现在雨下得很大。', '我', 'pouring 常用来形容大雨；不是轻微下雨。'],
      ['Did you bring an umbrella?', '你带伞了吗？', '我'],
      ["Let's find somewhere to take shelter.", '我们找个地方避雨吧。', '我'],
      ['How about getting a coffee instead?', '要不改去喝咖啡？', '我'],
      ['That sounds like a better plan.', '这个安排听起来更好。', '朋友'],
      ['Do you think it will clear up later?', '你觉得晚点会放晴吗？', '朋友'],
      ["I'd rather stay indoors today.", '我今天更想待在室内。', '我', 'would rather 后接动词原形；本句表达这次的选择。'],
      ['Can we leave it until tomorrow?', '我们可以留到明天吗？', '我', 'it 指双方已明确的活动；不清楚时直接说 leave the walk until tomorrow。'],
    ],
    dialogues: [
      ['出门前调整计划', '说明天气，提出替代', [
        ['我', 'Are we still meeting at the park at two?', '我们还是两点在公园见吗？'],
        ['朋友', "Looks like it's about to rain. Do you still want to go?", '看样子快下雨了，你还想去吗？'],
        ['我', "I'd rather stay indoors. How about getting a coffee instead?", '我更想待室内，要不改喝咖啡？'],
        ['朋友', 'That sounds good. The cafe by the station?', '可以，车站旁边那家咖啡馆？'],
        ['我', 'Yes. Can we keep the same time?', '对，还按原来的时间吗？'],
        ['朋友', 'Sure. See you there at two.', '可以，两点在那里见。'],
      ]],
      ['散步时雨变大', '即时商量安全去处', [
        ['朋友', "It's only a light drizzle. Shall we keep walking?", '只是毛毛雨，我们继续走吗？'],
        ['我', 'For a few minutes. I have an umbrella.', '再走几分钟吧，我有伞。'],
        ['朋友', "It's getting heavier. It's pouring now.", '越下越大，现在雨很大了。'],
        ['我', "Let's take shelter in that cafe.", '去那家咖啡馆避雨吧。'],
        ['朋友', 'Good idea. Do you think it will clear up later?', '好主意，你觉得晚点会放晴吗？'],
        ['我', "I'm not sure. We can decide after a drink.", '不确定，喝点东西后再决定吧。'],
      ]],
    ],
    branches: [
      ['朋友更想改期', '保留邀请但确认新时间', [
        ['朋友', "I'd rather leave the walk until tomorrow.", '我更想把散步留到明天。'],
        ['我', 'That works. Are you free in the morning?', '可以，你上午有空吗？'],
        ['朋友', 'Yes, after ten.', '有，十点以后。'],
        ['我', "Let's meet at ten thirty, then.", '那就十点半见。'],
      ]],
      ['没有带伞', '不勉强继续走', [
        ['我', "I forgot my umbrella, and it's starting to rain.", '我忘带伞了，而且开始下雨了。'],
        ['朋友', 'We can share mine until we get to the cafe.', '到咖啡馆前可以一起用我的。'],
        ['我', "Thanks. Let's take the shortest route.", '谢谢，走最近的路吧。'],
        ['朋友', 'Sure. The cafe is just across the road.', '好，咖啡馆就在马路对面。'],
      ]],
    ],
    practice: { substitutions: ['把 park entrance 换成 station exit，约车站出口。', '把 coffee 换成 lunch，提出改去吃午饭。', '把 tomorrow 换成 next Saturday，商量改期。'], responses: [['Do you still want to walk?', '今天更想待室内。', "I'd rather stay indoors today."], ["It's pouring.", '提议找地方避雨。', "Let's find somewhere to take shelter."], ['Can we do tomorrow instead?', '答应并问时间。', 'Sure. What time works for you?']], task: '约一次散步，说明天气变化并提出替代；确认改后的地点和时间。' },
  }),
  D17: defineLesson('D17', {
    scenario: '进书店找一本轻松、不太长的英文小说。向店员询问分类和推荐，先读几页再决定；没库存时问订购方式。',
    phrases: ['something light to read 轻松的读物', 'the fiction section 小说区', 'a paperback 平装书', 'browse for a while 逛一会儿', 'order a copy 订一本', 'a quick read 可以较快读完的书'],
    core: [
      ["I'm looking for something light to read.", '我想找点轻松的读物。', '顾客'],
      ['Where is the fiction section?', '小说区在哪里？', '顾客'],
      ['Could you recommend a short novel?', '能推荐一本短篇幅的小说吗？', '顾客'],
      ["I'd prefer something not too difficult.", '我更想要不太难的。', '顾客'],
      ['Have you read this one?', '你读过这本吗？', '顾客'],
      ["It's an easy read, with short chapters.", '它读起来比较轻松，章节很短。', '店员', 'easy read 指相对容易读的书，不保证适合所有学习者。'],
      ['Is there a paperback edition?', '有平装版吗？', '顾客'],
      ['Can I read a few pages before I decide?', '我能先读几页再决定吗？', '顾客', 'a few 是少量但有几页；与 few 表示很少、几乎没有的语气不同。'],
      ["I'm just browsing, thanks.", '我先随便看看，谢谢。', '顾客', '礼貌表示暂时不用帮忙；并不承诺一定买书。'],
      ['Do you have this title in stock?', '这本书有现货吗？', '顾客'],
      ['Could you order a copy for me?', '能帮我订一本吗？', '顾客'],
      ['How long would that take?', '那大概要多久？', '顾客'],
    ],
    dialogues: [
      ['获得合适推荐', '说清长度和难度偏好', [
        ['店员', 'Can I help you find anything?', '需要帮你找什么吗？'],
        ['顾客', "I'm looking for a short novel, something light to read.", '我想找一本短一点、轻松的小说。'],
        ['店员', 'Do you have a genre in mind?', '有想看的类型吗？'],
        ['顾客', "Maybe a mystery, but I'd prefer something not too difficult.", '悬疑类吧，但我想要不太难的。'],
        ['店员', 'This one has short chapters and clear language.', '这本章节短，语言清楚易懂。'],
        ['顾客', 'Thanks. Could I read a few pages before I decide?', '谢谢，我能先读几页再决定吗？'],
        ['店员', 'Of course. Take your time.', '当然，慢慢看。'],
        ['顾客', 'Great, thanks for the recommendation.', '好，谢谢推荐。'],
      ]],
      ['看看不同版本', '核实版本后决定购买', [
        ['顾客', 'Is there a paperback edition of this book?', '这本书有平装版吗？'],
        ['店员', 'Yes, on the shelf below.', '有，在下面那层架子上。'],
        ['顾客', 'Is the text the same as in the hardcover?', '文字内容和精装版一样吗？'],
        ['店员', "Yes, it's the same edition, just a different binding.", '一样，是同一版本，只是装订不同。'],
        ['顾客', "Great. I'll take the paperback.", '好，我买平装版。'],
        ['店员', 'Sure. The checkout is by the entrance.', '好，收银台在入口旁边。'],
      ]],
    ],
    branches: [
      ['推荐的书太难', '具体说明希望调整的地方', [
        ['顾客', 'This looks a little difficult for me.', '这本看起来对我有点难。'],
        ['店员', 'Would you like something with simpler language?', '你想要语言更简单一些的吗？'],
        ['顾客', 'Yes, and shorter chapters if possible.', '想，如果可以，章节也短一点。'],
        ['店员', "Let's have a look at this collection of short stories.", '看看这本短篇小说集吧。'],
      ]],
      ['没现货', '问订购但不必立即下单', [
        ['店员', "We don't have that title in stock.", '这本现在没现货。'],
        ['顾客', 'Could you order a copy? How long would that take?', '能订一本吗，大概要多久？'],
        ['店员', "I can check availability and the delivery estimate for you.", '我可以帮你查供货情况和预计到货时间。'],
        ['顾客', 'Thanks. Please check before I place the order.', '谢谢，请先查一下，我再决定下单。'],
      ]],
    ],
    practice: { substitutions: ['把 short novel 换成 travel memoir，找旅行回忆录。', '把 fiction section 换成 history section，询问历史区。', '把 paperback 换成 hardcover，询问精装版。'], responses: [['Do you need any help?', '先随便看看。', "I'm just browsing, thanks."], ['What kind of book would you like?', '想找轻松的悬疑小说。', 'A light mystery would be nice.'], ["It's out of stock.", '问能否订购。', 'Could you order a copy for me?']], task: '描述自己的阅读偏好，得到推荐后试读，决定购买、再看看或询问订购。' },
  }),
  D18: defineLesson('D18', {
    scenario: '约朋友周五吃饭。原定六点，但你下班后需要休息，想改到七点；另练习朋友临时取消和自己礼貌拒绝邀请。',
    phrases: ['be up for it 愿意参与', 'make it later 改晚一点', 'come up 临时出现', 'take a rain check 改天再约', 'catch up 叙旧或交流近况', 'head off 离开'],
    core: [
      ['Are you free on Friday evening?', '你周五晚上有空吗？', '我'],
      ['Would you be up for dinner?', '你愿意一起吃晚饭吗？', '我', 'be up for 常用于较随意的邀约；正式商务邀请可以直接用 Would you like to...?'],
      ['That sounds good to me.', '我觉得不错。', '朋友'],
      ['Could we make it a bit later?', '我们能约晚一点吗？', '我'],
      ['How about seven instead of six?', '改成七点，不约六点，怎么样？', '我'],
      ["I'm pretty tired after work.", '我下班后挺累的。', '我'],
      ['Something has come up.', '临时有点事。', '朋友', 'come up 表示出现了新情况；取消约定时还应明确说自己不能参加。'],
      ['No worries. We can do another day.', '没关系，可以改天。', '我'],
      ['Thanks for asking, but I need a quiet evening.', '谢谢你邀请，不过我今晚想安静休息一下。', '我'],
      ['Could I take a rain check?', '可以改天再约吗？', '我', '表达希望改天参与；若不想再约，直接感谢并婉拒更清楚。'],
      ["It was good catching up.", '能聊聊近况真不错。', '我'],
      ["I'd better head off. See you soon.", '我该走了，回头见。', '我'],
    ],
    dialogues: [
      ['约饭并改时间', '给出原因和具体替代', [
        ['我', 'Are you free on Friday evening? Would you be up for dinner?', '周五晚上有空吗，要一起吃晚饭吗？'],
        ['朋友', 'Yes. How about six?', '有，六点怎么样？'],
        ['我', "Could we make it a bit later? I'm pretty tired after work.", '能约晚一点吗，我下班后挺累的。'],
        ['朋友', 'Sure. Would seven work?', '可以，七点行吗？'],
        ['我', 'Seven is perfect. The place near the station?', '七点正好，车站附近那家吗？'],
        ['朋友', "Yes. I'll meet you at the entrance.", '对，我在门口等你。'],
      ]],
      ['见面后自然收尾', '表达愉快并结束聊天', [
        ['朋友', 'How has your week been?', '这周过得怎么样？'],
        ['我', 'Busy, but good. It was nice to have a break tonight.', '忙，但还不错，今晚休息一下挺好的。'],
        ['朋友', 'Same here. We should do this again.', '我也是，下次再约吧。'],
        ['我', "Definitely. I'd better head off now, though.", '好啊，不过我现在该走了。'],
        ['朋友', 'Of course. Get home safely.', '好，回家路上注意安全。'],
        ['我', 'Thanks. It was good catching up. See you soon.', '谢谢，聊聊近况真不错，回头见。'],
      ]],
    ],
    branches: [
      ['朋友临时取消', '接住对方说明再确认后续', [
        ['朋友', "Sorry, something has come up. I can't make dinner tonight.", '抱歉，临时有事，今晚不能来吃饭了。'],
        ['我', 'No worries. Would you like to do another day?', '没关系，你想改天吗？'],
        ['朋友', 'Yes. Could we try next Tuesday?', '想，下周二可以吗？'],
        ['我', 'Tuesday works for me. We can confirm the time later.', '周二我可以，时间晚点再确认。'],
      ]],
      ['自己想婉拒', '清楚拒绝而不编理由', [
        ['朋友', 'Do you want to come out tonight?', '今晚想出来玩吗？'],
        ['我', 'Thanks for asking, but I need a quiet evening.', '谢谢邀请，不过今晚我想安静休息。'],
        ['朋友', 'No problem. Another time?', '没问题，改天？'],
        ['我', "Yes, I'd like that. Let's talk next week.", '好啊，我愿意，下周再商量。'],
      ]],
    ],
    practice: { substitutions: ['把 Friday evening 换成 Sunday afternoon，调整邀约。', '把 seven instead of six 换成 eight instead of seven，给出明确改期。', '把 dinner 换成 a walk，提议散步。'], responses: [['Something has come up.', '表示理解并提议改天。', 'No worries. We can do another day.'], ['Would seven work?', '答应并确认地点。', 'Yes. Shall we meet at the entrance?'], ['Do you want to come out tonight?', '谢邀但想休息。', 'Thanks for asking, but I need a quiet evening.']], task: '邀请朋友见面，协商时间地点；对方取消时自然接话，自己不想去时清楚婉拒。' },
  }),
};
