import { defineLesson } from './lesson-format.js';

// Append-only chapter IDs preserve favorites and downloaded lesson ownership.
export const practicalDailyChapters = [
  ['D36', '看牙医与说明牙齿问题', 'At the dentist', 'LifeBuoy', '生活服务', '描述牙痛 · 了解治疗 · 确认费用', 'One of my back teeth hurts when I bite down.', '我咬东西时有一颗后牙会疼。'],
  ['D37', '银行办事与银行卡问题', 'At the bank', 'Receipt', '生活服务', '开户材料 · 冻结卡片 · 核查交易', 'What documents do I need to open an account?', '开户需要哪些材料？'],
  ['D38', '邮局寄件与国际包裹', 'Sending a parcel', 'Package', '生活服务', '选寄送方式 · 如实申报 · 查询延误', 'I would like to send this parcel overseas.', '我想把这个包裹寄到国外。'],
  ['D39', '搬家与预约搬运服务', 'Planning a move', 'Package', '居家与生活', '说明物品 · 核对报价 · 处理损坏', 'Could I get a quote for moving to a new apartment?', '能给我一份搬到新公寓的报价吗？'],
  ['D40', '开车停车与处理小事故', 'Driving and parking', 'CarFront', '出行与社交', '核对停车规则 · 描述碰撞 · 联系援助', 'Am I allowed to park here?', '我可以在这里停车吗？'],
  ['D41', '表达不同意见与处理误会', 'Disagreeing and clarifying', 'MessagesSquare', '出行与社交', '说明分歧 · 核对意思 · 商定下一步', 'I see your point, but I have a different concern.', '我明白你的观点，不过我有另一个顾虑。'],
  ['D42', '道歉、补救与接受道歉', 'Apologizing and making amends', 'MessagesSquare', '出行与社交', '承担责任 · 提出补救 · 接受或暂缓回应', 'I am sorry I kept you waiting.', '对不起，让你等了这么久。'],
  ['D43', '礼貌设定边界与拒绝请求', 'Setting boundaries', 'Hand', '出行与社交', '清楚拒绝 · 保护隐私 · 应对反复请求', 'I cannot help with that this weekend.', '这个周末我没法帮这个忙。'],
  ['D44', '介绍自己的家乡与推荐路线', 'Sharing your hometown', 'Trees', '出行与社交', '介绍特色 · 推荐行程 · 按兴趣调整', 'My hometown is a small city near the coast.', '我的家乡是一座靠近海岸的小城市。'],
  ['D45', '介绍中国茶与一起喝茶', 'Sharing Chinese tea', 'Coffee', '购物与饮食', '介绍茶类 · 描述滋味 · 尊重饮用偏好', 'Would you like to try some Chinese tea?', '你想尝尝中国茶吗？'],
];

export const practicalWorkChapters = [
  ['W12', '反馈问题与协商解决方案', 'Reporting issues and agreeing on solutions', 'MessagesSquare', '职场沟通', '描述影响 · 提供证据 · 商定方案与期限', 'Could we review this issue and agree on the next steps?', '我们能一起核查这个问题，并商定下一步吗？'],
  ['W13', '谈工作条件与薪资待遇', 'Discussing employment terms', 'Receipt', '职场沟通', '询问薪资结构 · 协商条件 · 核对书面 offer', 'Could you share the salary range for this role?', '能介绍这个岗位的薪资范围吗？'],
];

// All procedures, prices and policies are practice examples, not medical or legal guidance.
export const practicalLessons = {
  D36: defineLesson('D36', {
    scenario: '后牙咬合时疼痛，你预约牙科检查，说明症状和药物过敏，了解检查、治疗选项与费用。后来复诊或询问付款安排。这里练习沟通，不据症状自行诊断；治疗和紧急程度由专业人员评估。',
    phrases: ['bite down 咬合', 'sensitive to cold 对冷敏感', 'a dental appointment 牙科预约', 'treatment options 治疗选项', 'an itemized estimate 分项估价', 'a follow-up appointment 复诊预约'],
    core: [
      ['One of my back teeth hurts when I bite down.', '我咬东西时有一颗后牙会疼。', '患者', 'bite down 指上下牙咬合；说明哪一侧、什么情况下疼，比只说 toothache 更具体。'],
      ['It started two days ago.', '这是两天前开始的。', '患者'],
      ['That tooth is sensitive to cold drinks.', '那颗牙遇到冷饮会敏感。', '患者'],
      ['My gum feels swollen around this tooth.', '这颗牙周围的牙龈感觉肿了。', '患者'],
      ['Do you have an appointment available today?', '今天还有可以预约的时间吗？', '患者'],
      ['I have a drug allergy. What information do you need?', '我有药物过敏，你需要哪些信息？', '患者', 'drug allergy 指药物过敏；告知具体药名和反应，不能用笼统表述替代病史核对。'],
      ['Could you explain what the examination involves?', '能说明检查包括什么吗？', '患者'],
      ['What are my treatment options?', '我有哪些治疗选择？', '患者', 'options 是可考虑的选项；还可以问每种的风险、好处和不治疗的影响。'],
      ['Will the procedure require a local anesthetic?', '这个操作需要局部麻醉吗？', '患者'],
      ['Please let me know before you start.', '开始前请先告诉我。', '患者'],
      ['Could I have an itemized estimate before deciding?', '我决定前能拿到分项估价吗？', '患者', 'estimate 是估价，最终费用可能因检查结果而变；itemized 要求列出各项。'],
      ['When should I arrange a follow-up appointment?', '我应该什么时候安排复诊？', '患者'],
    ],
    dialogues: [
      ['预约并描述症状', '说明位置、诱因与持续时间', [
        ['患者', 'Do you have an appointment available today?', '今天还有可以预约的时间吗？'],
        ['接待员', 'Let me check. What seems to be the problem?', '我查一下，具体是什么问题？'],
        ['患者', 'One of my back teeth hurts when I bite down. It started two days ago.', '我咬东西时有一颗后牙会疼，这是两天前开始的。'],
        ['接待员', 'Which side is it on?', '在哪一侧？'],
        ['患者', 'The lower right side. That tooth is also sensitive to cold drinks.', '右下侧，那颗牙遇到冷饮也会敏感。'],
        ['接待员', 'We have an opening at three. The dentist will assess your symptoms.', '三点有一个空位，牙医会评估你的症状。'],
        ['患者', 'Thank you. I have a drug allergy. What information do you need?', '谢谢，我有药物过敏，你需要哪些信息？'],
        ['接待员', 'Please bring the medication name and details of the reaction, if available.', '如果有的话，请带上药名和过敏反应的具体信息。'],
      ]],
      ['了解检查和治疗选择', '知情后再决定，先问清费用', [
        ['患者', 'Could you explain what the examination involves?', '能说明检查包括什么吗？'],
        ['牙医', 'I will examine the tooth first, then explain whether any further tests are needed.', '我先检查这颗牙，再说明是否需要进一步检查。'],
        ['患者', 'Please let me know before you start.', '开始前请先告诉我。'],
        ['牙医', 'Of course. We can pause if you need a break.', '当然，你需要休息时我们可以暂停。'],
        ['患者', 'After the examination, could we discuss my treatment options?', '检查后能讨论我的治疗选择吗？'],
        ['牙医', 'Yes. I will explain the findings, benefits and risks of each suitable option.', '可以，我会说明检查结果，以及每种适用选择的好处和风险。'],
        ['患者', 'Could I have an itemized estimate before deciding?', '我决定前能拿到分项估价吗？'],
        ['牙医', 'Certainly. We will review the costs before you consent to treatment.', '当然，我们会在你同意治疗前核对费用。'],
      ]],
    ],
    branches: [
      ['治疗后仍有不适', '描述变化并联系诊所评估', [
        ['患者', 'I had treatment yesterday, and the pain is getting worse.', '我昨天接受了治疗，现在疼痛在加重。'],
        ['接待员', 'I will ask the dentist to advise you. Can you describe what has changed?', '我会请牙医给你建议，能描述一下有哪些变化吗？'],
        ['患者', 'The area feels more swollen. Should I come back for a check?', '那个部位感觉更肿了，我需要回来检查吗？'],
        ['接待员', 'Let us arrange an assessment and confirm how soon you should be seen.', '我们来安排评估，并确认你需要多快就诊。'],
      ]],
      ['费用与保险不清楚', '向适当机构核实，不把预估当承诺', [
        ['患者', 'Does this estimate include all the planned treatment?', '这份估价包含所有计划中的治疗吗？'],
        ['接待员', 'It lists the planned items. Additional work would be discussed separately.', '它列出了计划项目，额外治疗会另行讨论。'],
        ['患者', 'Could I get a copy to check with my insurance provider?', '我能拿一份副本向保险公司核实吗？'],
        ['接待员', 'Yes. Your provider can confirm the coverage and any conditions.', '可以，保险公司可以确认保障范围和相关条件。'],
      ]],
    ],
    practice: {
      substitutions: ['把 the lower right side 换成 the upper left side，描述不同位置。', '把 cold drinks 换成 hot drinks，说明不同诱因。', '把 two days ago 换成 last night，交代开始时间。'],
      responses: [['When did it start?', '说明两天前开始，并补充咬合时疼。', 'It started two days ago, and it hurts when I bite down.'], ['Do you have any allergies?', '告知有药物过敏，并提出提供药名和反应。', 'I have a drug allergy. I can give you the medication name and details of the reaction.'], ['Would you like to go ahead?', '请求先了解选择和分项费用。', 'Could we review the treatment options and the itemized estimate first?']],
      task: '模拟牙科预约和就诊：说明位置、诱因、时间和过敏信息，询问检查、治疗选择及费用；治疗后症状变化时联系诊所，不自行判断病因。',
    },
  }),
  D37: defineLesson('D37', {
    scenario: '你在银行询问开户材料和账户费用；后来银行卡找不到，向官方客服申请冻结并核查一笔不认识的交易。账户资格、补卡和争议处理时限因银行而异，不能套用练习中的流程。',
    phrases: ['open an account 开户', 'proof of address 住址证明', 'a monthly fee 月费', 'freeze my card 冻结卡片', 'a replacement card 补发卡片', 'an unrecognized transaction 不认识的交易'],
    core: [
      ['What documents do I need to open an account?', '开户需要哪些材料？', '客户', 'open an account 是开立账户；具体证件、居住或税务要求要向银行核实。'],
      ['Do you accept this as proof of address?', '你们接受这个作为住址证明吗？', '客户'],
      ['Is there a monthly fee for this account?', '这个账户有月费吗？', '客户'],
      ['Is there a minimum balance requirement?', '有最低余额要求吗？', '客户', 'minimum balance 是最低余额；问清适用条件及未达到时的费用。'],
      ['How can I make an international transfer?', '我怎样办理国际转账？', '客户'],
      ['Could you explain the exchange rate and all the fees?', '能说明汇率和全部费用吗？', '客户'],
      ['I cannot find my card. Could you freeze it?', '我找不到卡了，能冻结它吗？', '客户', 'freeze 常指暂时停用卡片；永久挂失、注销和补卡是不同操作，要确认。'],
      ['Can I request a replacement card?', '我可以申请补发一张卡吗？', '客户'],
      ['I do not recognize this transaction on my statement.', '账单上这笔交易我不认识。', '客户', '不认识交易时先要求核查，描述日期、金额和商户；不要直接断言已确认诈骗。'],
      ['What is the process for disputing this charge?', '对这笔扣款提出异议需要走什么流程？', '客户'],
      ['How can I check the status of my request?', '我怎样查询申请的处理状态？', '客户'],
      ['Could I have a reference number for this case?', '能给我这个事项的查询编号吗？', '客户'],
    ],
    dialogues: [
      ['开户前核对条件', '材料、月费与余额要求', [
        ['客户', 'What documents do I need to open an account?', '开户需要哪些材料？'],
        ['工作人员', 'The requirements depend on the account and your circumstances. Let us check them together.', '要求取决于账户类型和你的情况，我们一起核对。'],
        ['客户', 'Do you accept this utility bill as proof of address?', '你们接受这份公用事业账单作为住址证明吗？'],
        ['工作人员', 'I will check the date and the name on it against our requirements.', '我会按我们的要求核对日期和姓名。'],
        ['客户', 'Is there a monthly fee for this account?', '这个账户有月费吗？'],
        ['工作人员', 'There can be a fee, with conditions for waiving it. Here is the fee schedule.', '可能有月费，也有免收条件，这是收费表。'],
        ['客户', 'Is there a minimum balance requirement? Could you explain the conditions?', '有最低余额要求吗？能解释一下条件吗？'],
        ['工作人员', 'Certainly. We can compare the available accounts before you choose.', '当然，我们可以在你选择前比较可开立的账户。'],
      ]],
      ['卡片丢失与陌生扣款', '通过官方渠道核查并留存编号', [
        ['客户', 'I cannot find my card. Could you freeze it?', '我找不到卡了，能冻结它吗？'],
        ['客服', 'We need to verify your identity through our secure process first.', '我们需要先通过安全流程核验你的身份。'],
        ['客户', 'I understand. I also do not recognize this transaction on my statement.', '明白，账单上这笔交易我也不认识。'],
        ['客服', 'Once verification is complete, we can review the date, amount and merchant.', '核验完成后，我们可以核对日期、金额和商户。'],
        ['客户', 'What is the process for disputing this charge?', '对这笔扣款提出异议需要走什么流程？'],
        ['客服', 'I will explain the steps and any supporting information we need. A refund is not confirmed yet.', '我会说明步骤和所需证明，目前还没有确认退款。'],
        ['客户', 'Could I have a reference number for this case?', '能给我这个事项的查询编号吗？'],
        ['客服', 'Yes. You can use it when contacting us through the official app or phone line.', '可以，通过官方 App 或电话联系我们时可以使用。'],
      ]],
    ],
    branches: [
      ['卡片支付被拒', '区别卡片限制与商户问题', [
        ['客户', 'My card was declined, but my account shows enough money.', '刷卡被拒了，但账户显示余额充足。'],
        ['客服', 'Let us check for card restrictions or a transaction limit.', '我们检查一下卡片限制或交易限额。'],
        ['客户', 'Can you confirm whether the card is still active?', '能确认这张卡是否仍可使用吗？'],
        ['客服', 'Yes. We will review its status before suggesting the next step.', '可以，我们会先核对状态，再建议下一步。'],
      ]],
      ['国际转账费用', '确认实收金额与中间费用', [
        ['客户', 'Could you explain the exchange rate and all the fees?', '能说明汇率和全部费用吗？'],
        ['工作人员', 'This quote shows our fees. Other banks may also charge fees.', '这份报价列出了我们的费用，其他银行也可能收费。'],
        ['客户', 'Can you confirm how much the recipient is expected to receive?', '能确认预计收款人会收到多少吗？'],
        ['工作人员', 'I can explain the estimate and which charges are not yet known.', '我可以解释预估金额，以及哪些费用尚不确定。'],
      ]],
    ],
    practice: {
      substitutions: ['把 monthly fee 换成 international transfer fee，询问国际转账费用。', '把 this utility bill 换成 this rental agreement，核实另一种住址证明。', '把 freeze it 换成 explain how to replace it，询问补卡流程。'],
      responses: [['Which transaction do you mean?', '指出账单上的交易，请对方核对商户。', 'I mean this transaction on my statement. Could you check the merchant?'], ['What would you like to know about the account?', '询问月费与最低余额要求。', 'Is there a monthly fee or a minimum balance requirement?'], ['We have opened a case.', '索取编号和查询进度的方式。', 'Could I have a reference number, and how can I check the status?']],
      task: '模拟开户咨询和丢卡求助：核实材料及费用，通过银行官方渠道处理卡片状态和陌生交易，索取查询编号；不向非官方联系人透露密码或验证码。',
    },
  }),
  D38: defineLesson('D38', {
    scenario: '你到邮局寄国际礼物包裹，说明内装物品，比较邮费、预计时效与追踪服务，并了解海关申报。之后发现轨迹未更新，申请查询。禁限寄规则、税费和到达时间由目的地及承运方确认。',
    phrases: ['send a parcel 寄包裹', 'estimated delivery time 预计送达时间', 'a tracking number 追踪编号', 'a customs declaration 海关申报', 'restricted items 限寄物品', 'proof of postage 寄件凭证'],
    core: [
      ['I would like to send this parcel overseas.', '我想把这个包裹寄到国外。', '寄件人', 'parcel 常用于英式英语，package 在美式英语中也常用；需说明目的地。'],
      ['What delivery options are available?', '有哪些寄送方式可选？', '寄件人'],
      ['What is the estimated delivery time?', '预计多久送达？', '寄件人', 'estimated 表示预估，海关或运输延误可能影响到达时间，不能当作保证。'],
      ['Does this service include tracking?', '这项服务包含物流追踪吗？', '寄件人'],
      ['Could you check whether these items can be sent?', '能核实这些物品是否可以寄吗？', '寄件人'],
      ['How should I fill in the customs declaration?', '海关申报单应该怎么填写？', '寄件人', '按真实物品、数量和价值填写；gift 不代表自动免税或可以不申报。'],
      ['It contains two cotton scarves and a greeting card.', '里面有两条棉围巾和一张贺卡。', '寄件人'],
      ['Could you check the recipient address and postal code?', '能核对收件地址和邮政编码吗？', '寄件人'],
      ['Is additional cover available for loss or damage?', '可以另外购买丢失或损坏保障吗？', '寄件人', 'cover 在这里指保障；询问适用物品、赔付条件和除外情况。'],
      ['Could I have proof of postage and the tracking number?', '能给我寄件凭证和追踪编号吗？', '寄件人'],
      ['The tracking information has not changed for several days.', '追踪信息好几天没有变化了。', '寄件人'],
      ['How can I request an investigation?', '我怎样申请查询调查？', '寄件人'],
    ],
    dialogues: [
      ['比较寄送方式并申报', '先核实物品，再选择服务', [
        ['寄件人', 'I would like to send this parcel overseas. What delivery options are available?', '我想把这个包裹寄到国外，有哪些寄送方式可选？'],
        ['工作人员', 'Which country is it going to, and what does it contain?', '寄到哪个国家？里面是什么？'],
        ['寄件人', 'It is going to Canada. It contains two cotton scarves and a greeting card.', '寄到加拿大，里面有两条棉围巾和一张贺卡。'],
        ['工作人员', 'Let us check the restrictions and weigh the parcel before comparing services.', '我们先核对限制并称重，再比较服务。'],
        ['寄件人', 'What is the estimated delivery time, and does the service include tracking?', '预计多久送达？服务包含物流追踪吗？'],
        ['工作人员', 'This option includes tracking. The delivery estimate does not include possible customs delays.', '这项服务包含追踪，预计时效未计入可能的海关延误。'],
        ['寄件人', 'How should I fill in the customs declaration?', '海关申报单应该怎么填写？'],
        ['工作人员', 'List the actual items, quantities and values. I can explain the fields.', '填写真实物品、数量和价值，我可以说明各个栏目。'],
      ]],
      ['查询迟迟未更新的包裹', '核对记录和后续联系时间', [
        ['寄件人', 'The tracking information has not changed for several days.', '追踪信息好几天没有变化了。'],
        ['客服', 'Could you give me the tracking number and the posting date?', '能提供追踪编号和寄出日期吗？'],
        ['寄件人', 'Here they are. Has the parcel reached the destination country?', '在这里，包裹到目的地国家了吗？'],
        ['客服', 'The latest scan does not confirm that yet.', '最新扫描记录还不能确认这一点。'],
        ['寄件人', 'How can I request an investigation?', '我怎样申请查询调查？'],
        ['客服', 'I will check whether it is eligible now and explain the documents we need.', '我会核实现在是否符合申请条件，并说明所需材料。'],
        ['寄件人', 'When should I contact you again if there is no update?', '如果没有更新，我应该什么时候再联系你们？'],
        ['客服', 'Let us confirm the follow-up date and record the case reference.', '我们来确认后续联系日期，并记下查询编号。'],
      ]],
    ],
    branches: [
      ['不确定能否寄电池', '告知具体物品，请承运方确认', [
        ['寄件人', 'This device has a battery. Can it be sent using this service?', '这个设备带电池，能用这项服务寄吗？'],
        ['工作人员', 'We need to check the battery type and whether it is installed in the device.', '我们需要核对电池类型，以及是否装在设备中。'],
        ['寄件人', 'I can show you the specifications. Are there packing requirements?', '我可以提供规格，有包装要求吗？'],
        ['工作人员', 'We will check the applicable rules before accepting it.', '我们会在接收前核实适用规定。'],
      ]],
      ['收件人被要求缴税', '区分邮费与目的地费用', [
        ['寄件人', 'The recipient was asked to pay a customs charge. Was that included in the postage?', '收件人被要求缴海关费用，这包含在邮费里吗？'],
        ['客服', 'That depends on the service. Let us check the terms on your receipt.', '这取决于服务，我们核对一下凭证上的条款。'],
        ['寄件人', 'How can the recipient verify the payment request?', '收件人怎样核实缴费通知？'],
        ['客服', 'They should check through the official carrier or customs channel for their location.', '应通过当地承运方或海关的官方渠道核实。'],
      ]],
    ],
    practice: {
      substitutions: ['把 Canada 换成另一目的地，再询问可用服务。', '把 two cotton scarves 换成 one book，重新说明物品和数量。', '把 estimated delivery time 换成 total postage，询问总邮费。'],
      responses: [['What does it contain?', '如实说明两条棉围巾和一张贺卡。', 'It contains two cotton scarves and a greeting card.'], ['Would you like the tracked service?', '确认预计时效和费用后再选择。', 'What is the estimated delivery time, and how much does it cost?'], ['The latest scan has not changed.', '询问调查流程和再次联系日期。', 'How can I request an investigation, and when should I contact you again?']],
      task: '模拟寄国际包裹：说明目的地及真实物品，核实禁限寄和申报要求，比较时效、费用与保障，保存凭证；延误时凭编号申请查询。',
    },
  }),
  D39: defineLesson('D39', {
    scenario: '你预约从三楼公寓搬到另一处住址，说明楼梯、家具和包装需要，要求书面报价；搬家当日核对范围，发生损坏时留存照片并询问处理。报价、保障与索赔条件以实际合同为准。',
    phrases: ['a moving quote 搬家报价', 'an itemized quote 分项报价', 'a flight of stairs 一段楼梯', 'packing service 打包服务', 'fragile items 易碎物品', 'report damage 报告损坏'],
    core: [
      ['Could I get a quote for moving to a new apartment?', '能给我一份搬到新公寓的报价吗？', '客户', 'quote 是报价；应确认是固定报价还是可能调整的估价，以及适用条件。'],
      ['The pickup address is on the third floor, with no lift.', '搬出地址在三楼，没有电梯。', '客户'],
      ['There are two flights of stairs.', '有两段楼梯。', '客户', 'flight of stairs 指连续一段台阶；楼层编号因地区而异，直接报楼梯段数更清楚。'],
      ['We have a sofa, a desk and about twenty boxes.', '我们有一张沙发、一张书桌和大约二十个箱子。', '客户'],
      ['Do you offer a packing service?', '你们提供打包服务吗？', '客户'],
      ['Does the quote include taking the bed apart?', '报价包含拆床吗？', '客户'],
      ['Are there extra fees for stairs or parking?', '楼梯搬运或停车会额外收费吗？', '客户'],
      ['Could you send me an itemized quote in writing?', '能把书面的分项报价发给我吗？', '客户', 'in writing 要求书面确认，便于核对物品、时间、附加费和取消条款。'],
      ['What arrival window should I expect?', '你们预计会在哪个时间段到达？', '客户'],
      ['Please keep these fragile boxes upright.', '这些易碎物品箱请保持直立。', '客户'],
      ['I noticed this table was damaged during the move.', '我发现这张桌子在搬运过程中受损了。', '客户'],
      ['What information do you need to review a damage claim?', '审核损坏索赔需要哪些信息？', '客户', 'claim 是提出赔偿申请，不代表已经获得赔偿；先核实证据、时限和保障条件。'],
    ],
    dialogues: [
      ['预约前核对报价', '楼梯、物品和拆装范围', [
        ['客户', 'Could I get a quote for moving to a new apartment?', '能给我一份搬到新公寓的报价吗？'],
        ['客服', 'Yes. Could you describe the addresses and the items?', '可以，能描述搬出搬入地址和物品吗？'],
        ['客户', 'The pickup address is on the third floor, with no lift. There are two flights of stairs.', '搬出地址在三楼，没有电梯，有两段楼梯。'],
        ['客服', 'Is there a lift at the new address, and how much are you moving?', '新地址有电梯吗？要搬多少东西？'],
        ['客户', 'There is a lift there. We have a sofa, a desk and about twenty boxes.', '那里有电梯，我们有一张沙发、一张书桌和大约二十个箱子。'],
        ['客服', 'Thank you. We also need to check vehicle access and parking at both addresses.', '谢谢，还需要核对两处的车辆通行和停车条件。'],
        ['客户', 'Does the quote include taking the bed apart? Could you send an itemized quote in writing?', '报价包含拆床吗？能发一份书面分项报价吗？'],
        ['客服', 'Yes. We will list the agreed items, services and any extra fees before you book.', '可以，预约前我们会列出商定的物品、服务和额外费用。'],
      ]],
      ['搬运当日确认', '保护物品并核查新收费', [
        ['客户', 'Before you start, could we check the list together?', '开始前我们能一起核对清单吗？'],
        ['搬运员', 'Of course. Are these the twenty boxes listed in the booking?', '当然，这些是预约里列出的二十个箱子吗？'],
        ['客户', 'Yes. Please keep these fragile boxes upright.', '是的，这些易碎物品箱请保持直立。'],
        ['搬运员', 'Understood. The truck cannot park as close as expected.', '明白，卡车不能像预计那样靠近停放。'],
        ['客户', 'Will that affect the price or the schedule?', '这会影响价格或时间安排吗？'],
        ['搬运员', 'I need to check with the office before confirming any change.', '确认任何变动前，我需要向办公室核实。'],
        ['客户', 'Please explain any extra fees before we agree to additional work.', '我们同意额外工作前，请先说明额外费用。'],
        ['搬运员', 'Certainly. Let us confirm the options with the office first.', '当然，我们先和办公室确认可选方案。'],
      ]],
    ],
    branches: [
      ['到达时间延误', '获取新的时间段，协调钥匙交接', [
        ['客户', 'The arrival window has passed. Could you give me an update?', '约定到达时间段已经过了，能告诉我最新情况吗？'],
        ['客服', 'The team is delayed. I will check their expected arrival.', '搬运团队延误了，我会核对预计到达时间。'],
        ['客户', 'I need to coordinate the key handover. Please confirm the new time window.', '我需要协调钥匙交接，请确认新的到达时间段。'],
        ['客服', 'I will contact the team and call you back with an update.', '我会联系团队，再打给你说明情况。'],
      ]],
      ['家具损坏', '记录现象并核对申请程序', [
        ['客户', 'I noticed this table was damaged during the move. I have photos from before and after.', '我发现这张桌子在搬运过程中受损了，我有搬前和搬后的照片。'],
        ['客服', 'Please keep those photos and send us the booking reference.', '请保留照片，并提供预约编号。'],
        ['客户', 'What information do you need to review a damage claim, and is there a deadline?', '审核损坏索赔需要哪些信息？有截止日期吗？'],
        ['客服', 'I will send you the process and the applicable coverage terms.', '我会把处理流程和适用的保障条款发给你。'],
      ]],
    ],
    practice: {
      substitutions: ['把 twenty boxes 换成 ten boxes and a bicycle，调整搬运清单。', '把 taking the bed apart 换成 putting the bed back together，核实组装服务。', '把 no lift 换成 a small lift，说明不同通行条件。'],
      responses: [['Are there stairs at the pickup address?', '说明有两段楼梯、没有电梯。', 'There are two flights of stairs and no lift.'], ['We may need to charge extra.', '要求先说明金额和原因，再确认。', 'Could you explain the amount and the reason before I agree?'], ['What happened to the table?', '描述损坏并提供前后照片。', 'I noticed damage after the move. I have photos from before and after.']],
      task: '模拟搬家预约：说明地址通行、物品和拆装需求，核对书面报价及时间段；延误时协调交接，损坏时提供证据并询问申请流程。',
    },
  }),
  D40: defineLesson('D40', {
    scenario: '你驾驶途中确认停车区域、付费时间和车辆限制；停车时发生轻微碰撞，先询问人员情况，再在安全前提下交换信息、记录现场并联系援助。交通法规、报警义务和事故程序因地区而异，向当地机构核实。',
    phrases: ['parking restrictions 停车限制', 'a parking meter 停车计时收费器', 'a minor collision 轻微碰撞', 'exchange contact details 交换联系方式', 'roadside assistance 道路救援', 'report the incident 报告事故'],
    core: [
      ['Am I allowed to park here?', '我可以在这里停车吗？', '司机', 'allowed 询问许可；有空车位也不代表可以停，要核对标志和限制。'],
      ['Does this space require a permit?', '这个车位需要停车许可吗？', '司机'],
      ['How do I pay for parking?', '停车费怎么付？', '司机'],
      ['What time does the parking restriction end?', '停车限制到几点结束？', '司机'],
      ['Is there a height limit for this car park?', '这个停车场有限高吗？', '司机'],
      ['I think our cars touched while I was reversing.', '我倒车时，我们的车好像碰到了。', '司机', 'reversing 指倒车；先陈述观察到的情况，不凭一句话确定责任或赔偿。'],
      ['Is anyone hurt?', '有人受伤吗？', '司机'],
      ['We should contact local emergency services if anyone needs urgent help.', '如果有人需要紧急救助，我们应联系当地紧急服务。', '司机'],
      ['Can we exchange contact and insurance details?', '我们可以交换联系方式和保险信息吗？', '司机', '通过合理、安全方式交换所需信息；各地要求不同，不把证件交给不明联系人。'],
      ['Could we take photos of the damage if it is safe?', '如果安全，我们可以拍下损坏情况吗？', '司机'],
      ['What is the local procedure for reporting this incident?', '当地报告这起事故的程序是什么？', '司机'],
      ['My car will not start. Could you arrange roadside assistance?', '我的车启动不了，能安排道路救援吗？', '司机', 'roadside assistance 是道路救援；先提供准确位置和危险情况，不在车流中自行检修。'],
    ],
    dialogues: [
      ['读不懂停车标志', '许可、付费和时间限制', [
        ['司机', 'Am I allowed to park here?', '我可以在这里停车吗？'],
        ['工作人员', 'This section is for permit holders. The public spaces are farther along.', '这一段供持许可证的人停放，公共车位在前面。'],
        ['司机', 'Thanks. How do I pay for parking in the public section?', '谢谢，公共区域停车费怎么付？'],
        ['工作人员', 'Use the meter by the entrance and check the sign for the maximum stay.', '使用入口旁的收费器，并查看标志上的最长停放时间。'],
        ['司机', 'Is payment required in the evening as well?', '晚上也需要付费吗？'],
        ['工作人员', 'The charging hours are listed on that sign. They can differ between streets.', '收费时段写在那个标志上，不同街道可能不同。'],
        ['司机', 'Could you show me which sign applies to this space?', '能指出哪块标志适用于这个车位吗？'],
        ['工作人员', 'Yes, the one beside the meter. Check it before leaving your car.', '可以，是收费器旁边那块，离开车辆前请核对。'],
      ]],
      ['停车时发生碰撞', '检查人员情况并确认当地程序', [
        ['司机甲', 'I think our cars touched while I was reversing. Is anyone hurt?', '我倒车时，我们的车好像碰到了，有人受伤吗？'],
        ['司机乙', 'I do not feel hurt at the moment. How about you?', '我目前没感觉受伤，你呢？'],
        ['司机甲', 'I do not feel hurt either. Are we in a safe place to talk?', '我也没感觉受伤，我们这里谈话安全吗？'],
        ['司机乙', 'We are away from the traffic, but let us stay alert.', '我们离开了车流，不过还是保持警觉。'],
        ['司机甲', 'Can we exchange contact and insurance details?', '我们可以交换联系方式和保险信息吗？'],
        ['司机乙', 'Yes. We should also check the local reporting requirements.', '可以，我们还应核对当地报告要求。'],
        ['司机甲', 'Could we take photos of the damage if it is safe?', '如果安全，我们可以拍下损坏情况吗？'],
        ['司机乙', 'Yes. Then we can contact the appropriate service and our insurers.', '可以，然后联系适当的服务机构和各自保险公司。'],
      ]],
    ],
    branches: [
      ['车辆无法启动', '描述位置并等待安全指引', [
        ['司机', 'My car will not start. Could you arrange roadside assistance?', '我的车启动不了，能安排道路救援吗？'],
        ['客服', 'Where are you, and is the vehicle creating a traffic hazard?', '你在哪里？车辆是否造成交通危险？'],
        ['司机', 'I am in the public car park by the station, in space B12, away from the road.', '我在车站旁公共停车场的 B12 车位，离道路有距离。'],
        ['客服', 'I will check the available assistance and explain how to wait safely.', '我会查询可用救援，并说明怎样安全等待。'],
      ]],
      ['有人需要急救', '准确报告位置与受伤情况', [
        ['司机', 'There has been a collision, and someone needs urgent medical help.', '这里发生了碰撞，有人需要紧急医疗救助。'],
        ['接线员', 'Tell me your exact location and what you can see.', '请告诉我准确位置和你看到的情况。'],
        ['司机', 'We are outside the north entrance of the station. One person is injured.', '我们在车站北入口外，有一人受伤。'],
        ['接线员', 'Stay on the line and follow the instructions I give you.', '请不要挂断，按我给你的指示操作。'],
      ]],
    ],
    practice: {
      substitutions: ['把 this space 换成 this loading area，询问装卸区域限制。', '把 by the station 换成 beside the supermarket，准确说明位置。', '把 will not start 换成 has a flat tyre，描述爆胎或轮胎没气的问题。'],
      responses: [['Do you have a parking permit?', '说明没有，并询问公共车位。', 'No. Where can I find a public parking space?'], ['What happened?', '陈述倒车时两车可能碰到，询问是否受伤。', 'I think our cars touched while I was reversing. Is anyone hurt?'], ['Where is your vehicle?', '报出停车场和具体车位。', 'It is in the public car park by the station, in space B12.']],
      task: '模拟停车咨询与碰撞沟通：核对许可、付费和时间限制；事故时先确认人员情况和安全，再按当地要求联系机构、交换信息并记录。',
    },
  }),
  D41: defineLesson('D41', {
    scenario: '你和朋友商量周末出行，对时间和交通方式有不同想法；一句简短回复又被误解为不想见面。练习先承认对方的想法，再说具体顾虑、核对理解并商定下一步。',
    phrases: ['see your point 理解你的观点', 'a different concern 另一个顾虑', 'clarify what I meant 澄清我的意思', 'jump to conclusions 急于下结论', 'meet halfway 各让一步', 'agree on the next step 商定下一步'],
    core: [
      ['I see your point, but I have a different concern.', '我明白你的观点，不过我有另一个顾虑。', '朋友甲', 'I see your point 表示理解对方的理由，不等于同意结论；后面说具体顾虑。'],
      ['I am worried that we will not have enough time.', '我担心我们时间不够。', '朋友甲'],
      ['Could we look at another option?', '我们能看看另一种选择吗？', '朋友甲'],
      ['What makes that option better for you?', '那个选择对你来说好在哪里？', '朋友甲'],
      ['I may have misunderstood what you meant.', '我可能误解了你的意思。', '朋友甲', 'may have misunderstood 承认理解可能有误，为澄清留空间，不必先判断谁对谁错。'],
      ['Did you mean we should leave earlier, rather than cancel?', '你的意思是早点出发，而不是取消吗？', '朋友甲'],
      ['That is not quite what I meant. Let me explain.', '这和我的意思不太一样，我解释一下。', '朋友甲'],
      ['My concern is the timing, not the idea itself.', '我担心的是时间安排，不是这个想法本身。', '朋友甲'],
      ['Let us check the details before we jump to conclusions.', '我们先核对细节，再下结论。', '朋友甲'],
      ['Could we meet halfway and choose a shorter route?', '我们能各让一步，选一条短一点的路线吗？', '朋友甲', 'meet halfway 在这里表示妥协，不是到两地中点见面；提出具体折中选项。'],
      ['I still see it differently, but I understand your reasoning.', '我仍有不同看法，但我理解你的理由。', '朋友甲'],
      ['Can we agree on the next step?', '我们能商定下一步吗？', '朋友甲', '可以保留不同观点，同时确认具体行动；不同意不必演变成人身评价。'],
    ],
    dialogues: [
      ['路线和时间意见不同', '把分歧转成可比较的选择', [
        ['朋友乙', 'I would like to do the full coastal walk on Saturday.', '我想周六走完整条海岸步道。'],
        ['朋友甲', 'I see your point, but I have a different concern. I need to be home by four.', '我明白你的想法，不过我有另一个顾虑，我四点前需要到家。'],
        ['朋友乙', 'The full route has the best views.', '完整路线的景色最好。'],
        ['朋友甲', 'Could we look at another option? What makes that route better for you?', '我们能看看另一种选择吗？那条路线对你来说好在哪里？'],
        ['朋友乙', 'I mainly want to see the lighthouse at the far end.', '我主要想看远端的灯塔。'],
        ['朋友甲', 'Could we meet halfway and take the bus to the lighthouse, then walk back part of the way?', '我们能各让一步，坐公交到灯塔，再步行回来一段吗？'],
        ['朋友乙', 'That could work if the bus runs early enough.', '如果公交够早发车，这样可以。'],
        ['朋友甲', 'Let us check the timetable and agree on a departure time.', '我们查一下时刻表，商定出发时间。'],
      ]],
      ['短消息造成误会', '复述理解，再解释真实意思', [
        ['朋友乙', 'Your message sounded as if you did not want to meet.', '你的消息听起来像不想见面。'],
        ['朋友甲', 'I am sorry it came across that way. That is not quite what I meant.', '抱歉让你有那种感觉，这和我的意思不太一样。'],
        ['朋友乙', 'You only said the plan was difficult.', '你只说这个计划很难办。'],
        ['朋友甲', 'My concern is the timing, not the idea itself. I still want to see you.', '我担心的是时间安排，不是想法本身，我还是想见你的。'],
        ['朋友乙', 'Did you mean we should leave earlier, rather than cancel?', '你的意思是早点出发，而不是取消吗？'],
        ['朋友甲', 'Yes. I should have made that clearer.', '是的，我应该说得更清楚。'],
        ['朋友乙', 'I understand now. Let us choose a time that works for both of us.', '现在明白了，我们选一个双方都方便的时间吧。'],
        ['朋友甲', 'Great. Would nine work for you?', '好，九点你方便吗？'],
      ]],
    ],
    branches: [
      ['仍然无法达成一致', '保留分歧并调整安排', [
        ['朋友甲', 'I still see it differently, but I understand your reasoning.', '我仍有不同看法，但我理解你的理由。'],
        ['朋友乙', 'I do not want to shorten the route this time.', '这次我不想缩短路线。'],
        ['朋友甲', 'Then I will skip this walk. Could we make another plan for next week?', '那这次徒步我就不参加了，下周能另约一次吗？'],
        ['朋友乙', 'Sure. Let us find something that fits both our schedules.', '可以，我们找个适合双方时间安排的活动。'],
      ]],
      ['对话开始激动', '暂停并约定重新沟通', [
        ['朋友甲', 'I am finding it hard to explain calmly right now. Could we take a break?', '我现在很难平静地解释，我们能暂停一下吗？'],
        ['朋友乙', 'Yes. When would you like to come back to it?', '可以，你想什么时候再谈？'],
        ['朋友甲', 'Could we talk again this evening, after we have checked the details?', '核对细节后，我们今晚能再谈吗？'],
        ['朋友乙', 'That works. Let us speak at seven.', '可以，我们七点谈。'],
      ]],
    ],
    practice: {
      substitutions: ['把 timing 换成 cost，表达对费用的顾虑。', '把 a shorter route 换成 a smaller group，提出具体折中方案。', '把 this evening 换成 tomorrow morning，约定再谈时间。'],
      responses: [['So you want to cancel?', '澄清想提前出发，而非取消。', 'That is not quite what I meant. I would like to leave earlier.'], ['Why do you disagree?', '说明担心时间不够，承认对方理由。', 'I understand your reasoning, but I am worried that we will not have enough time.'], ['We cannot agree on the route.', '建议各让一步并核对细节。', 'Could we meet halfway and choose a shorter route? Let us check the details first.']],
      task: '与搭档模拟一个行程分歧：复述对方理由，说明自己的具体顾虑，澄清一次误会并提出折中方案；不能一致时礼貌调整安排。',
    },
  }),
  D42: defineLesson('D42', {
    scenario: '你赴约迟到且没有及时告知，向朋友道歉并调整安排；另一次不小心弄坏借来的物品，提出具体补救。也练习接受道歉、要求改变，以及暂时需要空间时怎样回应。',
    phrases: ['keep someone waiting 让某人等', 'take responsibility 承担责任', 'make it right 补救', 'cover the repair cost 承担维修费', 'accept an apology 接受道歉', 'need some time 需要一些时间'],
    core: [
      ['I am sorry I kept you waiting.', '对不起，让你等了这么久。', '朋友甲', '指出具体行为比只说 sorry 更清楚；迟到后还要说明后续安排。'],
      ['I should have let you know sooner.', '我应该早点告诉你。', '朋友甲'],
      ['I understand that this affected your plans.', '我明白这影响了你的安排。', '朋友甲'],
      ['That was my mistake, and I take responsibility.', '那是我的失误，我承担责任。', '朋友甲', 'take responsibility 承担自己的行为责任，不接着把原因都推给对方。'],
      ['What can I do to make it right?', '我能做什么来补救？', '朋友甲'],
      ['I can cover the repair cost if that works for you.', '如果你觉得可以，我可以承担维修费。', '朋友甲'],
      ['I will check with you before borrowing it again.', '以后再借之前，我会先征求你的同意。', '朋友甲'],
      ['Thank you for apologizing.', '谢谢你道歉。', '朋友乙'],
      ['I appreciate you taking responsibility.', '谢谢你愿意承担责任。', '朋友乙'],
      ['I accept your apology, but I still need some time.', '我接受你的道歉，但还需要一些时间。', '朋友乙', '接受道歉可以与尚未平复并存；不必立刻说 It is fine。'],
      ['Please let me know earlier next time.', '下次请早点告诉我。', '朋友乙'],
      ['I am not ready to talk about it yet.', '我还没准备好谈这件事。', '朋友乙', 'yet 表示目前还没有准备好；可以表达边界，无需承诺何时原谅。'],
    ],
    dialogues: [
      ['迟到后道歉', '承认影响并调整当前安排', [
        ['朋友甲', 'I am sorry I kept you waiting. I should have let you know sooner.', '对不起，让你等了这么久，我应该早点告诉你。'],
        ['朋友乙', 'I was worried, and now we have less time for lunch.', '我挺担心的，而且现在午饭时间少了。'],
        ['朋友甲', 'I understand that this affected your plans. That was my mistake.', '我明白这影响了你的安排，那是我的失误。'],
        ['朋友乙', 'I need to leave in half an hour.', '我半小时后得走。'],
        ['朋友甲', 'Would you prefer a quick coffee now, or should we reschedule lunch?', '你想现在简单喝杯咖啡，还是改天吃午饭？'],
        ['朋友乙', 'A quick coffee is fine. Please let me know earlier next time.', '简单喝杯咖啡可以，下次请早点告诉我。'],
        ['朋友甲', 'I will. If I am delayed again, I will message as soon as I know.', '我会的，下次延误时，我一知道就发消息。'],
        ['朋友乙', 'Thank you for apologizing. Let us get a coffee nearby.', '谢谢你道歉，我们在附近喝杯咖啡吧。'],
      ]],
      ['弄坏借来的物品', '提出补救，由对方选择', [
        ['朋友甲', 'I damaged the lamp I borrowed from you. I am sorry, and I take responsibility.', '我弄坏了借你的台灯，对不起，我承担责任。'],
        ['朋友乙', 'What happened to it?', '它怎么坏的？'],
        ['朋友甲', 'I knocked it off the desk. The shade is cracked.', '我把它碰下了书桌，灯罩裂了。'],
        ['朋友乙', 'I would like to check whether it can be repaired first.', '我想先看看能不能修。'],
        ['朋友甲', 'Of course. I can cover the repair cost if that works for you.', '当然，如果你觉得可以，我可以承担维修费。'],
        ['朋友乙', 'Thank you. I will get a quote and discuss it with you.', '谢谢，我会问个报价，再和你商量。'],
        ['朋友甲', 'I will also check with you before borrowing it again.', '以后再借之前，我也会先征求你的同意。'],
        ['朋友乙', 'I appreciate you taking responsibility. Let us agree on the repair first.', '谢谢你愿意承担责任，我们先商定维修的事。'],
      ]],
    ],
    branches: [
      ['还需要时间', '接受边界，不追着要求原谅', [
        ['朋友甲', 'I am sorry about what I said. Can we talk?', '对我说的话，我很抱歉，我们能谈谈吗？'],
        ['朋友乙', 'Thank you for apologizing, but I am not ready to talk about it yet.', '谢谢你道歉，但我还没准备好谈这件事。'],
        ['朋友甲', 'I understand. I will give you some space.', '我理解，我会给你一些空间。'],
        ['朋友乙', 'Thank you. I will let you know if I want to discuss it.', '谢谢，如果我想谈，会告诉你。'],
      ]],
      ['同样的问题重复发生', '要求可观察的改变', [
        ['朋友乙', 'I accept your apology, but this has happened more than once.', '我接受你的道歉，但这已经发生不止一次了。'],
        ['朋友甲', 'You are right. I need to change how I handle this.', '你说得对，我需要改变处理方式。'],
        ['朋友乙', 'Please confirm the time in advance and message me if it changes.', '请提前确认时间，有变化就发消息给我。'],
        ['朋友甲', 'I will do that. Let us confirm our next plan now.', '我会这样做，我们现在确认下次的安排吧。'],
      ]],
    ],
    practice: {
      substitutions: ['把 kept you waiting 换成 missed your call，针对具体行为道歉。', '把 repair cost 换成 replacement cost，讨论对方认可的补救。', '把 borrowing it 换成 changing the plan，说明以后先征求同意。'],
      responses: [['You did not tell me you would be late.', '承认应早点告知，不辩解。', 'You are right. I should have let you know sooner. I am sorry.'], ['The lamp is damaged.', '承担责任并提出维修补救。', 'That was my mistake. I can cover the repair cost if that works for you.'], ['Are we okay now?', '说明接受道歉但还需要时间。', 'I accept your apology, but I still need some time.']],
      task: '模拟迟到或损坏物品后的沟通：说清行为、承认影响、提出具体补救和以后改变；交换角色，练习接受道歉或表达暂时需要空间。',
    },
  }),
  D43: defineLesson('D43', {
    scenario: '朋友临时请你周末帮忙、反复问私人问题，或要求借你不愿外借的电脑。练习清楚拒绝、说明有限的帮助范围，以及对方继续施压时重复边界并结束对话。',
    phrases: ['not available 没有空', 'keep something private 保持某事私密', 'not comfortable with 对……感到不自在', 'lend something out 把东西借出去', 'respect a decision 尊重决定', 'leave it there 到此为止'],
    core: [
      ['I cannot help with that this weekend.', '这个周末我没法帮这个忙。', '自己', '明确说明不能帮的事项和时间；不需要为了礼貌编造原因。'],
      ['I am not available on Saturday.', '我周六没空。', '自己'],
      ['I can help for an hour, but I cannot stay all day.', '我可以帮一小时，但不能待一整天。', '自己'],
      ['I would rather keep that private.', '那件事我更愿意保持私密。', '自己', 'would rather keep that private 是礼貌而清楚的隐私边界，不必继续提供细节。'],
      ['I am not comfortable discussing my salary.', '我不太愿意讨论自己的工资。', '自己'],
      ['Please check with me before sharing my photos.', '分享我的照片前，请先征求我的同意。', '自己'],
      ['I do not lend out my work laptop.', '我不把工作电脑借出去。', '自己'],
      ['Thanks for thinking of me, but I will pass this time.', '谢谢你想到我，不过这次我就不参加了。', '自己', 'pass this time 在邀请语境中表示这次不参加；不是把东西递给别人。'],
      ['I understand you need help, but my answer is still no.', '我理解你需要帮助，但我的答复仍然是不可以。', '自己'],
      ['Could we change the subject?', '我们能换个话题吗？', '自己'],
      ['Please respect my decision.', '请尊重我的决定。', '自己'],
      ['I have explained my decision. Let us leave it there.', '我已经说明了决定，这件事就到这里吧。', '自己', 'leave it there 表示停止讨论；如果继续施压，可以结束谈话，不必反复辩解。'],
    ],
    dialogues: [
      ['临时请求超出可用时间', '拒绝整天帮忙，明确有限范围', [
        ['朋友', 'Could you help me move on Saturday? It might take all day.', '周六能帮我搬家吗？可能要一整天。'],
        ['自己', 'I cannot help with that this weekend. I am not available on Saturday.', '这个周末我没法帮这个忙，我周六没空。'],
        ['朋友', 'Could you cancel your plans? I really need help.', '你能取消安排吗？我真的需要帮忙。'],
        ['自己', 'I understand you need help, but my answer is still no.', '我理解你需要帮助，但我的答复仍然是不可以。'],
        ['朋友', 'Is there another time you could help?', '有别的时间可以帮忙吗？'],
        ['自己', 'I can help pack for an hour on Friday evening, but I cannot stay all evening.', '我周五晚上可以帮忙打包一小时，但不能待一整晚。'],
        ['朋友', 'That would help. Would six to seven work?', '那也有帮助，六点到七点可以吗？'],
        ['自己', 'Yes. Let us keep it to that hour.', '可以，就按这一小时安排吧。'],
      ]],
      ['私人问题和照片分享', '说明隐私边界并请求尊重', [
        ['朋友', 'How much do you earn now?', '你现在赚多少钱？'],
        ['自己', 'I am not comfortable discussing my salary. I would rather keep that private.', '我不太愿意讨论自己的工资，那件事我更愿意保持私密。'],
        ['朋友', 'I was just curious.', '我只是好奇。'],
        ['自己', 'I understand. Could we change the subject?', '我理解，我们能换个话题吗？'],
        ['朋友', 'Sure. Can I post the photo we took together?', '可以，我能发我们一起拍的照片吗？'],
        ['自己', 'Please check with me before sharing my photos. I would prefer not to post this one.', '分享我的照片前请先征求同意，这张我更希望不发。'],
        ['朋友', 'Okay, I will keep it private.', '好，我会不公开这张照片。'],
        ['自己', 'Thank you for respecting my decision.', '谢谢你尊重我的决定。'],
      ]],
    ],
    branches: [
      ['借工作电脑', '拒绝后不被替代保证说服', [
        ['朋友', 'Can I borrow your work laptop tonight?', '今晚能借你的工作电脑吗？'],
        ['自己', 'I do not lend out my work laptop.', '我不把工作电脑借出去。'],
        ['朋友', 'I promise I will be careful.', '我保证会小心。'],
        ['自己', 'I understand, but my decision is the same. Please respect it.', '我理解，但我的决定一样，请尊重它。'],
      ]],
      ['持续施压', '结束争论和当前对话', [
        ['朋友', 'Why will you not explain more?', '你为什么不多解释一点？'],
        ['自己', 'I have explained my decision. Let us leave it there.', '我已经说明了决定，这件事就到这里吧。'],
        ['朋友', 'I still want to discuss it.', '我还是想讨论。'],
        ['自己', 'I am ending this conversation now. We can talk about something else another time.', '我现在要结束这段对话，我们改天可以聊别的。'],
      ]],
    ],
    practice: {
      substitutions: ['把 my salary 换成 my relationship，拒绝讨论私人关系。', '把 my photos 换成 my phone number，请求分享前征求同意。', '把 an hour 换成 thirty minutes，准确限定帮助时间。'],
      responses: [['Can you stay all day?', '说明只能帮一小时。', 'I can help for an hour, but I cannot stay all day.'], ['Why not tell me your salary?', '清楚表达隐私边界并换话题。', 'I would rather keep that private. Could we change the subject?'], ['Please say yes just this once.', '重复拒绝并请求尊重决定。', 'I understand, but my answer is still no. Please respect my decision.']],
      task: '分别练习拒绝临时帮忙、私人问题和借工作设备；对方再问一次时保持相同答复。只在愿意且能做到时提出有限帮助，不为了结束施压而承诺。',
    },
  }),
  D44: defineLesson('D44', {
    scenario: '朋友想了解你的家乡并计划短暂停留。你介绍海边小城的生活、市场和步行路线，再根据半天时间、雨天或行动不便调整建议。家乡与路线为虚构练习；营业、交通和无障碍条件需实际核实。',
    phrases: ['a coastal city 海滨城市', 'known for 因……出名', 'a local market 当地市场', 'within walking distance 在步行可达范围内', 'a relaxed pace 悠闲的节奏', 'a step-free route 无台阶路线'],
    core: [
      ['My hometown is a small city near the coast.', '我的家乡是一座靠近海岸的小城市。', '介绍者', 'hometown 通常指成长或视为故乡的地方；可以与现在居住的城市不同。'],
      ['It is known for its seafood and old streets.', '那里以海鲜和老街出名。', '介绍者', 'known for 后接特色；可以说家乡闻名什么，不必夸成 everyone knows it。'],
      ['Life there moves at a fairly relaxed pace.', '那里的生活节奏相当悠闲。', '介绍者'],
      ['I grew up near the local market.', '我在当地市场附近长大。', '介绍者'],
      ['What kind of places would you like to see?', '你想看哪类地方？', '介绍者'],
      ['If you only have half a day, I would start at the old market.', '如果你只有半天，我会建议先去老市场。', '介绍者'],
      ['The waterfront is within walking distance of the market.', '从市场步行就能到海滨。', '介绍者', 'within walking distance 表示步行可达，但远近因人而异；可补充预计时长和路况。'],
      ['You could stop for lunch and then walk along the water.', '你可以停下来吃午饭，再沿水边散步。', '介绍者'],
      ['It is worth checking the opening hours before you go.', '出发前最好查一下营业时间。', '介绍者'],
      ['The bus is an option if you prefer not to walk.', '如果你不想步行，也可以考虑公交。', '介绍者'],
      ['Let us check whether there is a step-free route.', '我们查一下有没有无台阶路线。', '介绍者', 'step-free 仅说明没有台阶，不一定代表所有无障碍条件均满足；仍需核对坡度等。'],
      ['I can suggest an indoor plan if it rains.', '如果下雨，我可以推荐室内行程。', '介绍者'],
    ],
    dialogues: [
      ['聊家乡和成长经历', '描述具体地方，接住对方问题', [
        ['朋友', 'What is your hometown like?', '你的家乡是什么样的？'],
        ['介绍者', 'My hometown is a small city near the coast. It is known for its seafood and old streets.', '我的家乡是一座靠近海岸的小城市，以海鲜和老街出名。'],
        ['朋友', 'Did you grow up near the sea?', '你是在海边长大的吗？'],
        ['介绍者', 'Not right by the sea. I grew up near the local market, a short bus ride away.', '不是紧挨海边，我在当地市场附近长大，坐公交不远就能到海边。'],
        ['朋友', 'What do you miss most about it?', '你最想念那里什么？'],
        ['介绍者', 'I miss the morning market and having breakfast with my family.', '我想念早市，以及和家人一起吃早餐。'],
        ['朋友', 'Is it very busy?', '那里很忙碌吗？'],
        ['介绍者', 'The market can be busy, but life there generally moves at a relaxed pace.', '市场会很热闹，但总体生活节奏很悠闲。'],
      ]],
      ['安排半天的路线', '先问兴趣，再给可执行行程', [
        ['朋友', 'I may visit your hometown, but I only have half a day.', '我可能去你的家乡，不过只有半天。'],
        ['介绍者', 'What kind of places would you like to see?', '你想看哪类地方？'],
        ['朋友', 'I like local food and quiet walks.', '我喜欢当地食物和安静散步。'],
        ['介绍者', 'I would start at the old market. The waterfront is within walking distance.', '我会建议先去老市场，步行就能到海滨。'],
        ['朋友', 'Could I have lunch there before the walk?', '散步前可以在那里吃午饭吗？'],
        ['介绍者', 'Yes. You could stop for lunch and then walk along the water.', '可以，你可以停下来吃午饭，再沿水边散步。'],
        ['朋友', 'What should I check before I go?', '出发前应该核实什么？'],
        ['介绍者', 'Check the opening hours, the weather and the bus timetable for your return.', '核对营业时间、天气和返程公交时刻表。'],
      ]],
    ],
    branches: [
      ['下雨调整路线', '避免把室外安排硬塞给对方', [
        ['朋友', 'It looks as if it will rain during my visit.', '看起来我去的时候会下雨。'],
        ['介绍者', 'I can suggest an indoor plan. Would you prefer a museum or a cooking class?', '我可以推荐室内行程，你更喜欢博物馆还是烹饪课？'],
        ['朋友', 'A museum sounds good. Do I need to book?', '博物馆不错，需要预约吗？'],
        ['介绍者', 'Let us check its official information for tickets and opening hours.', '我们查看官方信息，核实票务和开放时间。'],
      ]],
      ['需要无台阶路线', '问清需求并核实条件', [
        ['朋友', 'I cannot manage long walks or stairs. Would this route work for me?', '我走不了很远，也不方便走台阶，这条路线适合我吗？'],
        ['介绍者', 'Let us check whether there is a step-free route and somewhere to rest.', '我们查一下有没有无台阶路线和休息的地方。'],
        ['朋友', 'A shorter route with a bus option would help.', '有公交可选的短路线会更方便。'],
        ['介绍者', 'I will look at a shorter plan and confirm access with the venues.', '我会看看更短的方案，并向场馆确认通行条件。'],
      ]],
    ],
    practice: {
      substitutions: ['把 near the coast 换成 in the mountains，用自己的家乡地理特征介绍。', '把 seafood and old streets 换成 tea and historic buildings，描述特色。', '把 half a day 换成 two days，调整建议而不只增加地点数量。'],
      responses: [['What is your hometown known for?', '介绍海鲜和老街。', 'It is known for its seafood and old streets.'], ['I only have half a day. Where should I go?', '先问兴趣，再建议市场和海滨。', 'What kind of places do you like? You could start at the market and then visit the waterfront.'], ['Are there stairs on the route?', '说明需核实无台阶路线。', 'Let us check whether there is a step-free route.']],
      task: '用真实家乡替换虚构小城，准备一分钟介绍；给半天游客设计两个主要停留点，交代交通、返程和需核实的信息，再分别为雨天和行动需求调整。',
    },
  }),
  D45: defineLesson('D45', {
    scenario: '朋友来做客，你介绍绿茶与乌龙茶、邀请品尝并描述滋味；对方怕烫或想少摄入咖啡因时，你询问偏好并提供替代。茶的泡法和礼仪因茶类、地区及家庭而异，不把一种做法说成全国通例。',
    phrases: ['loose-leaf tea 散叶茶', 'green tea 绿茶', 'oolong tea 乌龙茶', 'a light flavor 清淡的滋味', 'brew another cup 再泡一杯', 'contain caffeine 含咖啡因'],
    core: [
      ['Would you like to try some Chinese tea?', '你想尝尝中国茶吗？', '主人', '先邀请再倒茶；对方可以拒绝，不必把喝茶当作礼貌义务。'],
      ['This is green tea from Zhejiang.', '这是来自浙江的绿茶。', '主人'],
      ['I also have an oolong tea with a roasted aroma.', '我还有一款带烘焙香气的乌龙茶。', '主人'],
      ['I usually use loose-leaf tea rather than tea bags.', '我通常用散叶茶，而不是茶包。', '主人'],
      ['Would you prefer a light flavor or a stronger one?', '你喜欢滋味清淡一点，还是浓一点？', '主人', 'stronger 描述更浓的滋味，不等于能准确判断咖啡因含量。'],
      ['Let it cool a little before you take a sip.', '喝一小口之前，先让它稍微凉一点。', '主人'],
      ['What flavors can you notice?', '你能喝出哪些滋味？', '主人'],
      ['You can use fewer leaves if it tastes too strong.', '如果喝起来太浓，可以少放些茶叶。', '主人'],
      ['Would you like me to brew another cup?', '你想让我再泡一杯吗？', '主人'],
      ['This tea contains caffeine. Would you prefer something else?', '这款茶含咖啡因，你想换点别的吗？', '主人', '传统茶树茶通常含咖啡因；含量受茶叶和冲泡等影响，不能简单按颜色判断。'],
      ['There is no need to finish it if you do not like it.', '如果你不喜欢，不用勉强喝完。', '主人'],
      ['Tea customs vary between regions and families.', '各地区和家庭的饮茶习惯有所不同。', '主人', '说明自己熟悉的做法，可以说 In my family；避免说所有中国人都遵守同一礼仪。'],
    ],
    dialogues: [
      ['邀请朋友尝茶', '介绍来源和滋味，照顾温度', [
        ['主人', 'Would you like to try some Chinese tea?', '你想尝尝中国茶吗？'],
        ['客人', 'Yes, please. What kinds do you have?', '想，谢谢，你有哪些茶？'],
        ['主人', 'This is green tea from Zhejiang. I also have an oolong tea with a roasted aroma.', '这是来自浙江的绿茶，我还有一款带烘焙香气的乌龙茶。'],
        ['客人', 'I would like something light.', '我想喝清淡一点的。'],
        ['主人', 'Let us try the green tea. Let it cool a little before you take a sip.', '我们试试绿茶，喝一小口前先让它稍微凉一点。'],
        ['客人', 'Thank you. Do you use tea bags?', '谢谢，你用茶包吗？'],
        ['主人', 'I usually use loose-leaf tea. What flavors can you notice?', '我通常用散叶茶，你能喝出哪些滋味？'],
        ['客人', 'It tastes fresh, with a little sweetness at the end.', '喝起来很清新，最后有一点回甜。'],
      ]],
      ['边喝边聊家中习惯', '介绍个人经验，保留不同做法', [
        ['客人', 'Do people in China always serve tea this way?', '中国人总是这样泡茶待客吗？'],
        ['主人', 'Tea customs vary between regions and families. This is how I usually make it at home.', '各地区和家庭的饮茶习惯不同，这是我平时在家的泡法。'],
        ['客人', 'Can you use the leaves again?', '这些茶叶可以再泡吗？'],
        ['主人', 'For this tea, I often brew another cup with the same leaves. It depends on the tea.', '这款茶我经常用同样的茶叶再泡一杯，要看具体茶。'],
        ['客人', 'How do you decide how long to brew it?', '你怎么决定泡多久？'],
        ['主人', 'I start with the instructions on the package and adjust it to my taste.', '我先参考包装上的说明，再按口味调整。'],
        ['客人', 'Could we try a lighter cup next?', '下一杯我们能试试淡一点的吗？'],
        ['主人', 'Of course. We can use fewer leaves and adjust the brewing time.', '当然，可以少放些茶叶，并调整冲泡时间。'],
      ]],
    ],
    branches: [
      ['不想摄入咖啡因', '透明说明并提供明确替代', [
        ['客人', 'I am avoiding caffeine this evening. Does this tea contain any?', '我今晚想避免摄入咖啡因，这茶含咖啡因吗？'],
        ['主人', 'Yes, it does. Would you prefer warm water instead?', '含有，你想改喝温水吗？'],
        ['客人', 'Warm water would be great, thank you.', '温水就很好，谢谢。'],
        ['主人', 'Of course. I will bring you a cup.', '当然，我给你拿一杯。'],
      ]],
      ['不喜欢味道', '接受偏好，不劝对方勉强喝', [
        ['客人', 'This is a little too strong for me.', '这对我来说有点太浓了。'],
        ['主人', 'There is no need to finish it. Would you like a lighter cup or something else?', '不用勉强喝完，你想换杯淡的，还是换别的饮品？'],
        ['客人', 'Could I have a lighter cup?', '能给我一杯淡一点的吗？'],
        ['主人', 'Certainly. I will use fewer leaves this time.', '当然，这次我少放些茶叶。'],
      ]],
    ],
    practice: {
      substitutions: ['把 from Zhejiang 换成已核实的茶叶产地，练习介绍来源。', '把 a light flavor 换成 a roasted flavor，表达口味偏好。', '把 warm water 换成 another caffeine-free drink，先确认饮品确实不含咖啡因。'],
      responses: [['What tea is this?', '说明是浙江绿茶，并询问喜好。', 'This is green tea from Zhejiang. Do you prefer a light flavor?'], ['Is this how everyone drinks tea in China?', '说明习惯因地区和家庭不同。', 'Tea customs vary between regions and families. This is how I make it at home.'], ['I am avoiding caffeine.', '说明茶含咖啡因并提供温水。', 'This tea contains caffeine. Would you prefer warm water instead?']],
      task: '用手边一款来源明确的茶模拟待客：介绍茶类与滋味、询问偏好、提醒温度；对方不喜欢或避咖啡因时提供替代，并说明个人泡法不代表全国惯例。',
    },
  }),
  W12: defineLesson('W12', {
    scenario: '你发现报表导出缺行，向同事说明可复现步骤、影响范围和时间需求，共同核对临时方案与正式修复；另练习服务交付不符时基于约定协商。时间与故障均为虚构练习，避免在未确认前承诺根因或修复期限。',
    phrases: ['steps to reproduce 复现步骤', 'the affected records 受影响记录', 'a temporary workaround 临时替代方案', 'acceptance criteria 验收标准', 'a target date 目标日期', 'escalate an issue 升级处理问题'],
    core: [
      ['Could we review this issue and agree on the next steps?', '我们能一起核查这个问题，并商定下一步吗？', '反馈者', 'review 先一起核查；agree on 明确后续行动，而非只要求对方“尽快处理”。'],
      ['The export is missing some records from yesterday.', '导出结果缺少昨天的部分记录。', '反馈者'],
      ['Here are the steps to reproduce the problem.', '这是复现问题的步骤。', '反馈者'],
      ['I can share a sample with sensitive data removed.', '我可以提供一份去除敏感数据的样例。', '反馈者', '只分享排查所需且允许共享的数据；遮蔽截图不等于原文件也已去除敏感信息。'],
      ['This affects the report we need to send today.', '这影响了我们今天需要发送的报表。', '反馈者'],
      ['What do we know so far, and what still needs checking?', '目前已经确认什么，还有什么需要核查？', '反馈者'],
      ['Is there a temporary workaround we can use?', '有我们可以使用的临时替代方案吗？', '反馈者', 'workaround 是绕过问题的临时办法，不意味着根因已修复；需确认限制与风险。'],
      ['Could we agree on the acceptance criteria?', '我们能商定验收标准吗？', '反馈者'],
      ['Who will be responsible for each action?', '每项行动由谁负责？', '反馈者'],
      ['Can you confirm a realistic target date?', '能确认一个现实可行的目标日期吗？', '反馈者', 'target date 是目标时间，不自动等于承诺；同时确认依赖、风险和下一次进展同步。'],
      ['Please let us know if the timeline changes.', '如果时间安排变化，请告知我们。', '反馈者'],
      ['I will summarize the agreed actions in writing.', '我会把商定的行动整理成书面记录。', '反馈者'],
    ],
    dialogues: [
      ['说明故障及业务影响', '带证据反馈，区分已知与未知', [
        ['反馈者', 'Could we review this issue? The export is missing some records from yesterday.', '我们能核查这个问题吗？导出结果缺少昨天的部分记录。'],
        ['处理者', 'Which export did you use, and can you reproduce it?', '你用了哪个导出？能复现吗？'],
        ['反馈者', 'I used the daily report export. Here are the steps to reproduce the problem.', '我用了日报导出，这是复现问题的步骤。'],
        ['处理者', 'Could you share a sample so we can compare it with the source?', '能提供样例，让我们和原始数据比较吗？'],
        ['反馈者', 'I can share a sample with sensitive data removed. This affects the report due today.', '我可以提供去除敏感数据的样例，这影响今天到期的报表。'],
        ['处理者', 'We have confirmed the missing rows, but we have not confirmed the cause yet.', '我们确认了缺行，但还没确认原因。'],
        ['反馈者', 'Is there a temporary workaround we can use?', '有我们可以使用的临时替代方案吗？'],
        ['处理者', 'We will check an alternative export and validate its completeness before recommending it.', '我们会检查另一种导出，并在建议使用前验证完整性。'],
      ]],
      ['协商交付与验收', '明确责任、标准和进度同步', [
        ['反馈者', 'Could we agree on the acceptance criteria for the fix?', '我们能商定这次修复的验收标准吗？'],
        ['处理者', 'The export should contain all records matching the selected date and filters.', '导出应包含所有符合所选日期和筛选条件的记录。'],
        ['反馈者', 'We should also compare the record count and totals with the source report.', '我们还应把记录数和汇总值与原始报表比较。'],
        ['处理者', 'Agreed. I will handle the investigation, and our tester will verify those checks.', '同意，我负责排查，测试人员验证这些项目。'],
        ['反馈者', 'Can you confirm a realistic target date?', '能确认一个现实可行的目标日期吗？'],
        ['处理者', 'I need to finish the investigation first. I can give a progress update by three today.', '我需要先完成排查，今天三点前可以同步进展。'],
        ['反馈者', 'That works. Please let us know if the timeline changes. I will summarize the actions in writing.', '可以，时间安排有变化请告知，我会把行动整理成书面记录。'],
        ['处理者', 'Thank you. Please include the acceptance criteria and the next update time.', '谢谢，请把验收标准和下次同步时间也写进去。'],
      ]],
    ],
    branches: [
      ['服务交付不符', '对照约定提出解决选项', [
        ['客户', 'The delivered file does not include the fields we agreed on.', '交付的文件没有包含我们商定的字段。'],
        ['服务方', 'Could you point out the missing fields in the agreed specification?', '能在已商定的规格中指出缺少的字段吗？'],
        ['客户', 'Yes. Could we review the gap and agree on a revised delivery plan?', '可以，我们能核对差异并商定修订的交付计划吗？'],
        ['服务方', 'Let us confirm the scope and available options before setting a new date.', '我们先确认范围和可选方案，再确定新日期。'],
      ]],
      ['迟迟没有进展', '说明影响并申请适当升级', [
        ['反馈者', 'We have not received the agreed update, and the report is still blocked.', '我们还没收到约定的进展同步，报表仍无法完成。'],
        ['处理者', 'I am sorry. The investigation is taking longer than expected.', '抱歉，排查比预计花的时间更长。'],
        ['反馈者', 'Could we involve the team lead to agree on priorities and an interim plan?', '我们能请团队负责人一起商定优先级和临时方案吗？'],
        ['处理者', 'Yes. I will bring the evidence and current findings to that discussion.', '可以，我会带上证据和目前发现参加讨论。'],
      ]],
    ],
    practice: {
      substitutions: ['把 missing records 换成 incorrect totals，提供相应可复现证据。', '把 today 换成 by Friday morning，说明业务期限。', '把 a temporary workaround 换成 a revised delivery plan，协商不同层面的解决方案。'],
      responses: [['Can you reproduce the problem?', '提供复现步骤和去敏样例。', 'Yes. Here are the steps, and I can share a sample with sensitive data removed.'], ['We do not know the cause yet.', '询问临时方案和进展同步时间。', 'Is there a temporary workaround, and when can you give us an update?'], ['How will we know the fix works?', '要求按原始数据核对记录数和汇总值。', 'We should compare the record count and totals with the source report.']],
      task: '模拟一次问题反馈会：用现象、复现步骤和业务影响说明问题，区分已确认与待核查，商定临时方案、责任人、验收标准及下次进展时间，并复述书面行动项。',
    },
  }),
  W13: defineLesson('W13', {
    scenario: '你拿到岗位意向，询问税前基本工资、浮动奖金、工时、工作地点和试用期条款；再依据经验协商待遇，索取书面 offer 并核对回复期限。币种、税制、合同和福利因地区及公司而异，示例数字不代表市场行情。',
    phrases: ['salary range 薪资范围', 'gross annual base salary 税前年基本工资', 'a performance bonus 绩效奖金', 'working hours 工作时间', 'a written offer 书面录用通知', 'a probation period 试用期'],
    core: [
      ['Could you share the salary range for this role?', '能介绍这个岗位的薪资范围吗？', '候选人', 'range 是范围；先确认币种、税前税后及年薪月薪口径，再比较。'],
      ['Is that the gross annual base salary?', '那是税前年基本工资吗？', '候选人', 'gross 是税前，annual 是按年，base salary 是基本工资，不包含所有奖金福利。'],
      ['Which currency is the offer in?', '这份 offer 使用什么币种？', '候选人'],
      ['How is the performance bonus calculated?', '绩效奖金怎么计算？', '候选人'],
      ['Which benefits are included in the package?', '待遇方案包含哪些福利？', '候选人'],
      ['What are the usual working hours?', '通常的工作时间是什么？', '候选人'],
      ['How is overtime handled?', '加班怎么安排和处理？', '候选人'],
      ['Is remote or hybrid working available?', '可以远程或混合办公吗？', '候选人'],
      ['What are the terms of the probation period?', '试用期条款是什么？', '候选人', '确认期限、考核、工资和通知安排等；试用期不等于可以忽略当地劳动规则。'],
      ['Based on my experience, is there room to discuss the base salary?', '结合我的经验，基本工资还有协商空间吗？', '候选人'],
      ['Could you send the full terms in a written offer?', '能把完整条款写进书面 offer 发给我吗？', '候选人', 'full terms 要求核对完整条款；口头讨论的条件需在正式文件中确认。'],
      ['When would you need my response?', '你们需要我什么时候答复？', '候选人'],
    ],
    dialogues: [
      ['询问薪资和工作条件', '统一金额口径，核实奖金与工作方式', [
        ['候选人', 'Could you share the salary range for this role?', '能介绍这个岗位的薪资范围吗？'],
        ['招聘方', 'The range is sixty to seventy thousand pounds a year.', '范围是每年六万到七万英镑。'],
        ['候选人', 'Is that the gross annual base salary, with the bonus separate?', '那是税前年基本工资，奖金另外计算吗？'],
        ['招聘方', 'Yes. The performance bonus is separate and depends on the plan conditions.', '是的，绩效奖金另计，取决于奖金计划条件。'],
        ['候选人', 'How is the bonus calculated, and which benefits are included?', '奖金怎么计算，包含哪些福利？'],
        ['招聘方', 'I will send the current bonus plan and the benefits summary for you to review.', '我会发送当前奖金计划和福利摘要供你核对。'],
        ['候选人', 'What are the usual working hours, and is hybrid working available?', '通常工作时间是什么，可以混合办公吗？'],
        ['招聘方', 'Let us review the team schedule and the written policy together.', '我们一起核对团队安排和书面政策。'],
      ]],
      ['基于经验协商', '提出依据，留出核实和回复时间', [
        ['候选人', 'Thank you for the offer. Based on my experience, is there room to discuss the base salary?', '谢谢你们的 offer，结合我的经验，基本工资还有协商空间吗？'],
        ['招聘方', 'What figure did you have in mind?', '你期望什么数字？'],
        ['候选人', 'I was hoping for sixty-eight thousand pounds gross a year, given my experience leading similar projects.', '考虑到我有带领类似项目的经验，我希望税前年基本工资是六万八千英镑。'],
        ['招聘方', 'I will review that with the hiring manager. I cannot confirm a change yet.', '我会与招聘经理讨论，目前还不能确认调整。'],
        ['候选人', 'Thank you. Could you also confirm the terms of the probation period?', '谢谢，能同时确认试用期条款吗？'],
        ['招聘方', 'Yes. We will include those in the written offer.', '可以，我们会把它们写进书面 offer。'],
        ['候选人', 'When would you need my response after I receive the full terms?', '收到完整条款后，你们需要我什么时候答复？'],
        ['招聘方', 'Let us agree on a response deadline once the revised offer is ready.', '修订后的 offer 准备好后，我们再商定回复期限。'],
      ]],
    ],
    branches: [
      ['基本工资无法调整', '比较福利，不自动接受替代', [
        ['招聘方', 'We cannot increase the base salary for this role.', '这个岗位的基本工资无法提高。'],
        ['候选人', 'I understand. Is there flexibility on working arrangements or professional development support?', '我理解，工作安排或职业发展支持方面有调整空间吗？'],
        ['招聘方', 'We can discuss training support, but it would need approval.', '我们可以讨论培训支持，不过需要审批。'],
        ['候选人', 'Please confirm any approved changes in writing so I can review the full package.', '获批的调整请书面确认，让我核对完整待遇方案。'],
      ]],
      ['需要更多时间', '明确延期请求及期望答复日期', [
        ['招聘方', 'Could you respond by tomorrow?', '能明天前答复吗？'],
        ['候选人', 'I need a little more time to review the full terms. Could I respond by Friday?', '我需要多一点时间核对完整条款，能周五前答复吗？'],
        ['招聘方', 'Let me check whether we can extend the deadline.', '我核实一下能否延长截止时间。'],
        ['候选人', 'Thank you. Please let me know the confirmed date.', '谢谢，请告知确认后的日期。'],
      ]],
    ],
    practice: {
      substitutions: ['把 gross annual base salary 换成 gross monthly base salary，注意同步换算金额口径。', '把 hybrid working 换成 flexible starting hours，询问弹性上班时间。', '把 leading similar projects 换成与你真实经历相符的理由，不编造经验。'],
      responses: [['The offer is sixty-five thousand a year.', '确认币种、税前基本工资与奖金口径。', 'Which currency is that in, and is it the gross annual base salary with the bonus separate?'], ['What salary did you have in mind?', '提出示例期望并说明经验依据。', 'I was hoping for sixty-eight thousand pounds gross a year, given my experience leading similar projects.'], ['Can you accept by tomorrow?', '请求周五前回复，等待确认。', 'Could I respond by Friday? I need time to review the full terms.']],
      task: '模拟 offer 沟通：确认币种、税前工资周期、基本与浮动部分、工时、工作方式及试用期；用真实经验提出协商，核对书面条款和回复期限后再决定。',
    },
  }),
};
