import { defineLesson } from './lesson-format.js';

export const travelLessons = {
  T01: defineLesson('T01', {
    scenario: '去机场柜台值机，带一个行李箱和一个背包。询问托运、随身行李和登机地点；额度与费用请柜台核实，不把练习信息当作航空公司统一规定。',
    phrases: ['check in 值机', 'check a bag 托运行李', 'carry-on baggage 随身行李', 'a boarding pass 登机牌', 'a window seat 靠窗座位', 'the baggage allowance 行李额度'],
    core: [
      ["I'd like to check in for my flight.", '我想办理航班值机。', '旅客'],
      ['May I see your passport?', '能看一下你的护照吗？', '地勤'],
      ['I have one bag to check.', '我有一个包要托运。', '旅客', 'check a bag 是办理托运；check in 通常指旅客办理值机。'],
      ['Can I take this bag on board?', '这个包可以带上飞机吗？', '旅客'],
      ['What is the baggage allowance for my ticket?', '我的票有多少行李额度？', '旅客'],
      ['Does this bag meet the size limit?', '这个包符合尺寸限制吗？', '旅客'],
      ['Is there an extra fee?', '有额外费用吗？', '旅客'],
      ['Could I have a window seat if one is available?', '如果还有，能给我靠窗座位吗？', '旅客', 'if one is available 说明有空位才请求，不把偏好当成已确认安排。'],
      ['What time does boarding start?', '几点开始登机？', '旅客', 'boarding 是登机；departure 是起飞或出发，两个时间不能混用。'],
      ['Which gate should I go to?', '我应该去哪个登机口？', '旅客'],
      ['Please check the departure screens for updates.', '请查看出发信息屏上的更新。', '地勤'],
      ['Could you explain what I need to do next?', '能说明一下我接下来要做什么吗？', '旅客'],
    ],
    dialogues: [
      ['柜台值机', '确认托运和座位偏好', [
        ['旅客', "Hi, I'd like to check in for my flight.", '你好，我想办理值机。'],
        ['地勤', 'Of course. May I see your passport?', '当然，能看一下护照吗？'],
        ['旅客', 'Here you are. I have one bag to check.', '给你，我有一个包要托运。'],
        ['地勤', 'Please put it on the scale. Do you have a seat preference?', '请放到秤上，你有座位偏好吗？'],
        ['旅客', 'A window seat, if one is available.', '如果有，想要靠窗座位。'],
        ['地勤', "Let me check. I'll print your boarding pass after that.", '我查一下，之后给你打印登机牌。'],
        ['地勤', 'A window seat is available. Here is your boarding pass and bag receipt.', '有靠窗座位，这是登机牌和行李凭条。'],
        ['旅客', 'Thank you. I will keep them with me.', '谢谢，我会随身保管。'],
      ]],
      ['询问下一步', '区别登机开始和航班起飞', [
        ['旅客', 'What time does boarding start?', '几点开始登机？'],
        ['地勤', 'At ten twenty. Your flight departs at eleven.', '十点二十开始，航班十一点起飞。'],
        ['旅客', 'Which gate should I go to?', '去哪个登机口？'],
        ['地勤', 'Gate twelve for now. Please check the screens for changes.', '目前是十二号，请看屏幕留意变化。'],
        ['旅客', 'So I go through security first, then check the gate?', '所以先过安检，再确认登机口？'],
        ['地勤', "That's right. Follow the Departures signs.", '对，沿出发指示牌走。'],
      ]],
    ],
    branches: [
      ['行李超过额度', '问清选择和费用', [
        ['地勤', 'Your checked bag is over the allowance for this ticket.', '你的托运行李超出了这张票的额度。'],
        ['旅客', 'What are my options, and how much is the extra fee?', '我有哪些选择，额外费用是多少？'],
        ['地勤', 'I can check the fee, or you can reduce the weight before checking it.', '我可以查费用，你也可以先减轻重量再托运。'],
        ['旅客', 'Please check the fee before I decide.', '请先查费用，我再决定。'],
      ]],
      ['登机口变更', '核对航班编号', [
        ['旅客', 'The screen shows a different gate. Is this for flight AB one two three?', '屏幕显示了不同登机口，这是 AB123 航班吗？'],
        ['地勤', 'Yes, it has moved to gate eighteen.', '是的，改到了十八号。'],
        ['旅客', 'How do I get to gate eighteen from here?', '从这里怎么去十八号？'],
        ['地勤', 'Follow the signs along this corridor, then turn right.', '沿这条走廊的指示牌走，再右转。'],
      ]],
    ],
    practice: { substitutions: ['把 window seat 换成 aisle seat，请求靠过道座位。', '把 one bag 换成 two bags，说明托运数量。', '把 gate twelve 换成 gate twenty，确认登机口。'], responses: [['Do you have bags to check?', '一个箱子。', 'Yes, one suitcase.'], ['There is an extra fee.', '先问金额。', 'How much is it?'], ['The gate has changed.', '问新登机口。', 'Which gate should I go to now?']], task: '完成值机，确认行李规则和费用，区分登机与起飞时间，再核实登机口。' },
  }),
  T02: defineLesson('T02', {
    scenario: '乘飞机中途想要水和毯子，降落前询问转机。下一班登机口可能变化，到达后向地面工作人员核实；不把机组的时间估计当保证。',
    phrases: ['a blanket 毯子', 'still water 无气泡水', 'a connecting flight 转机航班', 'make the connection 赶上转机', 'transfer desk 中转服务台', 'boarding time 登机时间'],
    core: [
      ['Could I have some water, please?', '能给我点水吗？', '旅客'],
      ['Still or sparkling?', '无气泡还是气泡水？', '乘务员'],
      ['Still water, please.', '无气泡水，谢谢。', '旅客', 'still water 是无气泡水；不是形容水保持不动。'],
      ['Could I have a blanket?', '能给我一条毯子吗？', '旅客'],
      ['Would you mind letting me past?', '方便让我过去一下吗？', '旅客', '用于请邻座让路；Would you mind 后接动名词 letting。'],
      ['I have a connecting flight.', '我还要转机。', '旅客'],
      ['Will I have enough time to make my connection?', '我有足够时间赶上转机吗？', '旅客', 'make my connection 在这里是赶上转机，不是建立某种联系。'],
      ['Where can I check the next gate?', '哪里可以查下一程登机口？', '旅客'],
      ['Do I need to collect my checked bag?', '我需要领取托运行李吗？', '旅客'],
      ['Please confirm that at the transfer desk.', '请在中转服务台确认。', '乘务员'],
      ['My next flight starts boarding in thirty minutes.', '下一班还有三十分钟开始登机。', '旅客'],
      ['What should I do if I miss the connection?', '如果赶不上转机，我应该怎么办？', '旅客'],
    ],
    dialogues: [
      ['机上简单请求', '用品、选择和感谢', [
        ['旅客', 'Excuse me, could I have some water?', '不好意思，能给我点水吗？'],
        ['乘务员', 'Of course. Still or sparkling?', '当然，无气泡还是气泡水？'],
        ['旅客', 'Still water, please. Could I have a blanket as well?', '无气泡水，也能给我一条毯子吗？'],
        ['乘务员', "I'll check whether we have any left.", '我看看还有没有。'],
        ['旅客', 'Thank you. I appreciate it.', '谢谢，麻烦你了。'],
        ['乘务员', "You're welcome. I'll be back in a moment.", '不客气，我马上回来。'],
      ]],
      ['降落前问中转', '获取线索，到地面再确认', [
        ['旅客', 'I have a connecting flight. Will I have enough time?', '我还要转机，时间来得及吗？'],
        ['乘务员', 'How long is your connection?', '你的中转间隔多久？'],
        ['旅客', 'One hour, and our arrival has been delayed.', '一小时，而且我们到达延误了。'],
        ['乘务员', 'Please check with the transfer desk as soon as we land.', '降落后请尽快问中转服务台。'],
        ['旅客', 'Do I need to collect my checked bag?', '需要领取托运行李吗？'],
        ['乘务员', 'They can confirm that using your booking and bag tag.', '他们可以根据你的预订和行李标签确认。'],
      ]],
    ],
    branches: [
      ['想从邻座旁过去', '礼貌请求和回应', [
        ['旅客', 'Excuse me, would you mind letting me past?', '不好意思，方便让我过去一下吗？'],
        ['邻座', "Of course. I'll stand up.", '当然，我站起来。'],
        ['旅客', 'Thanks. I will be back in a few minutes.', '谢谢，我几分钟后回来。'],
        ['邻座', 'No problem.', '没问题。'],
      ]],
      ['转机时间很紧', '找工作人员协助', [
        ['旅客', 'My next flight starts boarding in thirty minutes. Can you help me find the gate?', '下一班还有三十分钟开始登机，能帮我找登机口吗？'],
        ['工作人员', 'May I see your boarding pass?', '能看一下登机牌吗？'],
        ['旅客', 'Here it is. What happens if I miss the connection?', '在这里，如果没赶上会怎样？'],
        ['工作人员', "Let's check the flight status first, then the airline can explain your options.", '先查航班状态，然后航空公司会说明可选方案。'],
      ]],
    ],
    practice: { substitutions: ['把 water 换成 tea，请求茶。', '把 thirty minutes 换成 twenty minutes，说明中转时间紧。', '把 blanket 换成 headphones，询问耳机。'], responses: [['Still or sparkling?', '选择无气泡水。', 'Still water, please.'], ['Do you have your boarding pass?', '递给对方。', 'Yes, here it is.'], ['Please check at the transfer desk.', '询问服务台位置。', 'Where is the transfer desk?']], task: '提出两个机上请求；转机时间紧时说清下一班信息，询问行李和后续选择。' },
  }),
  T03: defineLesson('T03', {
    scenario: '下午到酒店，预订在 Alex Chen 名下。询问早餐和退房时间；入住后发现空调无反应，先请检查，无法处理时商量换房。',
    phrases: ['a reservation under 姓名名下的预订', 'check-in time 入住时间', 'store the luggage 寄存行李', 'check out 退房', 'switch rooms 换房', 'send someone up 派人到房间'],
    core: [
      ['I have a reservation under Alex Chen.', '我有预订，姓名是 Alex Chen。', '住客', 'under 后接预订所用姓名，便于前台检索，不是房间位置。'],
      ['Could I check in now?', '我现在能办理入住吗？', '住客'],
      ['Could you store my luggage until the room is ready?', '房间准备好前能寄存行李吗？', '住客'],
      ['Is breakfast included?', '包含早餐吗？', '住客'],
      ['What time is check-out?', '几点退房？', '住客'],
      ['Is late check-out available?', '可以延迟退房吗？', '住客', '询问可用性后还需确认时间和费用，不能默认免费。'],
      ['Is there an extra charge for that?', '这个有额外收费吗？', '住客'],
      ["The air conditioning doesn't seem to be working.", '空调好像不工作了。', '住客', '先说明观察；再补充显示屏、风量等现象，比只说 broken 更可核查。'],
      ['Could someone come and take a look?', '能派人来看看吗？', '住客'],
      ['There is a lot of noise from the street.', '街上传来的噪音很大。', '住客'],
      ['Would it be possible to switch rooms?', '有可能换个房间吗？', '住客'],
      ["We'll check what is available.", '我们会查一下有没有空房。', '前台'],
    ],
    dialogues: [
      ['办理入住', '核对预订和服务时间', [
        ['住客', 'Hi, I have a reservation under Alex Chen.', '你好，我有预订，姓名是 Alex Chen。'],
        ['前台', 'Welcome. May I see your ID?', '欢迎，能看一下证件吗？'],
        ['住客', 'Here you are. Is breakfast included?', '给你，包含早餐吗？'],
        ['前台', 'Yes, from seven to ten in the restaurant.', '包含，餐厅七点到十点供应。'],
        ['住客', 'Thanks. What time is check-out?', '谢谢，几点退房？'],
        ['前台', 'Eleven a.m. Please ask us if you need a later time.', '上午十一点，需要更晚的话请问我们。'],
      ]],
      ['报告空调问题', '说明现象并请求检查', [
        ['住客', 'Hi, this is room three oh five. The air conditioning is not working.', '你好，这里是305房，空调不工作。'],
        ['前台', 'Is the display on?', '显示屏亮着吗？'],
        ['住客', "Yes, but no air is coming out. Could someone take a look?", '亮着，但没有风出来，能派人看看吗？'],
        ['前台', 'Of course. We can send someone up in about ten minutes.', '当然，大约十分钟后能派人上去。'],
        ['住客', "Thank you. I'll be in the room.", '谢谢，我会在房间里。'],
        ['前台', 'Sorry for the inconvenience.', '给你带来不便很抱歉。'],
      ]],
    ],
    branches: [
      ['提前到达', '寄存行李并问房间时间', [
        ['前台', 'Your room is not ready yet.', '你的房间还没准备好。'],
        ['住客', 'Could you store my luggage? When should I come back?', '能寄存行李吗，我什么时候回来？'],
        ['前台', 'Yes. Check-in starts at three this afternoon.', '能，今天下午三点开始入住。'],
        ['住客', "Great. I'll come back after three.", '好，我三点后回来。'],
      ]],
      ['空调暂时修不好', '询问换房及费用', [
        ['前台', 'We cannot fix the air conditioning tonight.', '今晚修不好空调。'],
        ['住客', 'Would it be possible to switch to a room with working air conditioning?', '能换到空调正常的房间吗？'],
        ['前台', 'We have another room of the same type available.', '有一间同房型的空房。'],
        ['住客', 'Thank you. Please confirm there is no extra charge before we move.', '谢谢，搬过去前请确认没有额外收费。'],
      ]],
    ],
    practice: { substitutions: ['把 air conditioning 换成 Wi-Fi，说明网络连接问题。', '把 room three oh five 换成 room four twelve，报告房号。', '把 breakfast 换成 parking，询问是否包含停车。'], responses: [['Your room is not ready.', '问是否可以寄存。', 'Could you store my luggage until it is ready?'], ['We can send someone up.', '确认自己在房间等。', "Thank you. I'll be in the room."], ['We have another room.', '问是否有费用。', 'Is there an extra charge to switch?']], task: '入住时核对两项服务，遇到设备问题时提供房号和现象；处理不了时协商换房。' },
  }),
  T04: defineLesson('T04', {
    scenario: '两人去餐厅，未预约，先问等位时间。其中一人对坚果过敏，需要明确说明并让服务员向厨房核实配料和交叉接触风险；无法确认时换选项。',
    phrases: ['a table for two 两人桌', 'the wait 等位时间', 'a nut allergy 坚果过敏', 'cross-contact 过敏原交叉接触', 'on the side 单独放旁边', 'split the bill 分摊账单'],
    core: [
      ['Do you have a table for two?', '有两人桌吗？', '顾客'],
      ['We do not have a reservation.', '我们没有预约。', '顾客'],
      ['How long is the wait?', '需要等多久？', '顾客'],
      ['What would you recommend?', '你有什么推荐？', '顾客'],
      ['Does this contain any nuts? I have a nut allergy.', '这里面有坚果吗？我对坚果过敏。', '顾客', 'allergy 是过敏，不是偏好；需要明确说出，不仅说 I don’t like nuts。'],
      ['Could you check the ingredients with the kitchen?', '能向厨房核实一下配料吗？', '顾客'],
      ['Could there be cross-contact with nuts during preparation?', '制作时可能接触到坚果吗？', '顾客', '询问交叉接触；只确认配料表不等于排除过敏原接触。'],
      ['Could I have the dressing on the side?', '能把沙拉酱单独放旁边吗？', '顾客'],
      ['We are ready to order.', '我们准备好点餐了。', '顾客'],
      ['Could we have the bill, please?', '能给我们账单吗？', '顾客'],
      ['Can we split the bill?', '我们可以分摊账单吗？', '顾客', '可以再说明 split it equally 平分，或 pay separately 各自付款。'],
      ['I think there is an extra item on the bill.', '账单上好像多了一项。', '顾客'],
    ],
    dialogues: [
      ['等位并点餐', '先问时间，后说明选择', [
        ['顾客', 'Do you have a table for two? We do not have a reservation.', '有两人桌吗，我们没预约。'],
        ['服务员', 'There is a short wait, about fifteen minutes.', '要稍等，大约十五分钟。'],
        ['顾客', "That's fine. Could you put our name down?", '可以，能登记一下我们的名字吗？'],
        ['服务员', 'Of course. I can give you a menu to look at while you wait.', '当然，等位时可以先给你一份菜单看看。'],
        ['顾客', 'Yes, please. We will need a few minutes to decide.', '想，我们需要几分钟决定。'],
        ['服务员', 'No problem. Let me know when you are ready.', '没问题，准备好后告诉我。'],
      ]],
      ['说明过敏并核实', '明确风险而不凭菜名猜', [
        ['顾客', 'Does the salad contain any nuts? I have a nut allergy.', '这份沙拉含坚果吗，我对坚果过敏。'],
        ['服务员', 'Let me check the ingredients with the kitchen.', '我向厨房核实一下配料。'],
        ['顾客', 'Thank you. Could you also ask about cross-contact during preparation?', '谢谢，也能问一下制作时是否会交叉接触吗？'],
        ['服务员', 'Yes. I will ask before taking your order.', '能，我会先问清楚再给你下单。'],
        ['顾客', 'If the kitchen cannot confirm, I will choose something else.', '如果厨房不能确认，我会选别的。'],
        ['服务员', 'Understood. I will bring back the information so you can decide.', '明白，我会带回核实的信息，让你决定。'],
      ]],
    ],
    branches: [
      ['账单多了一杯饮料', '指明项目并请求核查', [
        ['顾客', 'I think there is an extra drink on the bill.', '账单好像多算了一杯饮料。'],
        ['服务员', 'Which one do you mean?', '你指哪一杯？'],
        ['顾客', 'The second coffee. We only ordered one.', '第二杯咖啡，我们只点了一杯。'],
        ['服务员', 'Let me check the order and correct it if needed.', '我核对订单，需要的话会改正。'],
      ]],
      ['厨房无法确认过敏风险', '停止该项点单', [
        ['服务员', 'The kitchen cannot rule out contact with nuts.', '厨房无法排除接触坚果的可能。'],
        ['顾客', 'Thanks for checking. I will not order that dish.', '谢谢核实，那道菜我不点了。'],
        ['服务员', 'Would you like to look at other options?', '你想看看其他选项吗？'],
        ['顾客', 'Yes, but I need the kitchen to confirm the allergy information first.', '想，但需要厨房先确认过敏相关信息。'],
      ]],
    ],
    practice: { substitutions: ['把 table for two 换成 table for four，询问四人桌。', '把 nut allergy 换成 egg allergy，说明鸡蛋过敏并核实鸡蛋接触。', '把 second coffee 换成 bottle of water，指出账单多算项。'], responses: [['The wait is twenty minutes.', '接受并请登记。', 'That is fine. Could you put our name down?'], ['We cannot rule out contact with nuts.', '决定不点该菜。', 'Thanks for checking. I will not order that dish.'], ['Are you ready to order?', '还需要几分钟。', 'Could we have a few more minutes?']], task: '完成等位和点餐，清楚说明过敏并核实风险；结账时指出一项可核查的账单问题。' },
  }),
  T05: defineLesson('T05', {
    scenario: '在车站叫车去 River Hotel，约定 B 出口上车。出发前核对地址，下车时说清正门位置；司机只能在安全允许的位置停车。',
    phrases: ['the pickup point 上车点', 'the main entrance 正门', 'drop me off 让我下车', 'the fare 车费', 'a safe place to stop 安全停车处', 'across the road 马路对面'],
    core: [
      ['I am at exit B, next to the pharmacy.', '我在 B 出口，药店旁边。', '乘客'],
      ['Where is the pickup point?', '上车点在哪里？', '乘客'],
      ['Could you take me to this address?', '能带我去这个地址吗？', '乘客', 'take me to 用于请对方把自己送到目的地；可同时出示地址文字。'],
      ['Is this the River Hotel on King Street?', '这是 King Street 上的 River Hotel 吗？', '乘客'],
      ['How long will the trip take?', '这段路大概要多久？', '乘客'],
      ['Could you give me an estimate of the fare?', '能给我一个车费预估吗？', '乘客', 'estimate 是预估，不代表最终固定收费；有疑问需再问计费方式。'],
      ['Is there a toll on this route?', '这条路有过路费吗？', '乘客'],
      ['Could you drop me off at the main entrance?', '能让我在正门下车吗？', '乘客', 'drop someone off 指把人送到某处让其下车；停车位置还要符合现场限制。'],
      ['Please stop somewhere safe nearby.', '请在附近安全的地方停。', '乘客'],
      ['Is it within walking distance?', '可以步行过去吗？', '路人'],
      ['Should I turn left at the next junction?', '我应该在下个路口左转吗？', '路人'],
      ['Could I get a receipt for the trip?', '能给我这段行程的小票吗？', '乘客'],
    ],
    dialogues: [
      ['确认上车点和目的地', '用出口和地标定位', [
        ['司机', 'Hi, where are you waiting?', '你好，你在哪里等？'],
        ['乘客', 'At exit B, next to the pharmacy.', '在 B 出口，药店旁边。'],
        ['司机', 'The pickup point is just across the road.', '上车点就在马路对面。'],
        ['乘客', 'Okay. Before we leave, is the destination the River Hotel on King Street?', '好，出发前确认一下，是 King Street 上的 River Hotel 吗？'],
        ['司机', 'Yes, that is the address in the booking.', '对，订单里的地址就是那个。'],
        ['乘客', 'Great. How long will the trip take?', '好，车程大概要多久？'],
        ['司机', 'About twenty minutes, depending on traffic.', '大约二十分钟，取决于路况。'],
        ['乘客', 'Thanks. Please drop me off near the main entrance if you can.', '谢谢，如果可以，请让我在正门附近下车。'],
      ]],
      ['问步行路线', '复述转弯与地标', [
        ['路人', 'Excuse me, is the museum within walking distance?', '不好意思，博物馆可以步行过去吗？'],
        ['当地人', 'Yes, about ten minutes. Go straight, then turn left at the bank.', '可以，大约十分钟，直走，然后在银行左转。'],
        ['路人', 'At the bank, or at the next junction?', '在银行，还是下个路口？'],
        ['当地人', 'At the bank, which is at the second junction.', '在银行，它位于第二个路口。'],
        ['路人', 'Got it. Straight ahead, then left at the second junction.', '明白，直走，然后第二个路口左转。'],
        ['当地人', 'Exactly. The museum is on your right after that.', '对，之后博物馆在你右边。'],
      ]],
    ],
    branches: [
      ['同名酒店导致地址有误', '出发前纠正', [
        ['司机', 'We are going to the River Hotel on Lake Road.', '我们去 Lake Road 上的 River Hotel。'],
        ['乘客', 'Sorry, I need the one on King Street. Can we update the destination?', '不好意思，我要去 King Street 那家，能更新目的地吗？'],
        ['司机', 'Please change it in the app so the route and fare update.', '请在 App 里修改，路线和费用才会更新。'],
        ['乘客', 'Done. Could you check the new address before we leave?', '改好了，出发前能检查新地址吗？'],
      ]],
      ['正门不能停车', '改为安全附近位置', [
        ['乘客', 'Could you drop me off at the main entrance?', '能让我在正门下车吗？'],
        ['司机', 'We cannot stop directly outside it.', '不能直接停在门口。'],
        ['乘客', 'Please stop somewhere safe nearby, then.', '那请停在附近安全的位置。'],
        ['司机', 'There is a drop-off area around the corner.', '转角有个落客区。'],
      ]],
    ],
    practice: { substitutions: ['把 exit B 换成 exit D，说明上车出口。', '把 pharmacy 换成 bakery，用面包店定位。', '把 main entrance 换成 south entrance，说清南门。'], responses: [['Where are you waiting?', '在 B 出口药店旁。', 'At exit B, next to the pharmacy.'], ['We cannot stop here.', '请求安全附近位置。', 'Please stop somewhere safe nearby.'], ['Which hotel do you mean?', '补充街道名。', 'The River Hotel on King Street.']], task: '描述上车点、核对具体地址、询问时间和费用；下车地点受限时选择安全替代。' },
  }),
  T06: defineLesson('T06', {
    scenario: '下午两点坐出租车时可能把黑色手机落在后座。先联系平台或失物招领，提供行程时间和物品特征；找到相似物品后按对方要求证明所有权。',
    phrases: ['leave something behind 遗落物品', 'lost property 失物', 'the back seat 后座', 'a black case 黑色保护壳', 'proof of ownership 所有权凭证', 'pick it up 取回'],
    core: [
      ['I think I left my phone in the taxi.', '我想我把手机落在出租车里了。', '失主', 'leave something somewhere 指把东西留在某处；I think 保留位置尚未确认的信息。'],
      ['Who should I contact about a lost item?', '丢东西应该联系谁？', '失主'],
      ['It has a black case.', '它套着黑色保护壳。', '失主'],
      ['I last saw it on the back seat.', '我最后看到它是在后座。', '失主'],
      ['The trip ended at around two p.m.', '行程大约下午两点结束。', '失主'],
      ['I have the trip details in my account.', '我的账号里有行程记录。', '失主'],
      ['Has anyone handed it in?', '有人把它交来吗？', '失主', 'hand in 在失物场景里是交给工作人员，不是交作业。'],
      ['Could you check with the driver?', '能向司机核实一下吗？', '失主'],
      ['How can I prove it is mine?', '我怎样证明它是我的？', '失主'],
      ['Where can I pick it up?', '我在哪里可以取回？', '失主', 'pick up 在这里是去取回已经找到的物品，不是猜测东西还在原地。'],
      ['Do I need to bring any identification?', '需要带身份证明吗？', '失主'],
      ['Thank you for helping me look into it.', '谢谢你帮我核查。', '失主'],
    ],
    dialogues: [
      ['报告出租车遗失物', '给可检索的具体信息', [
        ['失主', 'I think I left my phone in a taxi this afternoon.', '我想今天下午把手机落在出租车里了。'],
        ['客服', 'Do you have the trip details?', '你有行程信息吗？'],
        ['失主', 'Yes. The trip ended at around two, at the River Hotel.', '有，大约两点在 River Hotel 结束。'],
        ['客服', 'Could you describe the phone?', '能描述一下手机吗？'],
        ['失主', 'It has a black case with a small red sticker on the back.', '它有黑色保护壳，背面有一张小红贴纸。'],
        ['客服', 'Please send the trip ID through the app. We will contact the driver.', '请通过 App 发来行程编号，我们会联系司机。'],
      ]],
      ['确认如何取回', '核实物品，不公开密码', [
        ['工作人员', 'A phone matching your description has been handed in.', '有人交来一部与你描述相符的手机。'],
        ['失主', 'That is good news. How can I prove it is mine?', '太好了，我怎样证明是我的？'],
        ['工作人员', 'Bring your ID and be ready to identify or unlock it in person.', '带上证件，准备当面辨认或解锁。'],
        ['失主', 'Where can I pick it up?', '在哪里取回？'],
        ['工作人员', 'At the lost property desk in the station, before six.', '六点前到车站失物招领台。'],
        ['失主', 'Thank you. I will come before six with my ID.', '谢谢，我会六点前带证件过去。'],
      ]],
    ],
    branches: [
      ['暂时没有找到', '问清后续联系方式', [
        ['客服', 'The driver has not found it yet.', '司机目前还没找到。'],
        ['失主', 'Could you let me know if it turns up?', '如果找到了，能告诉我吗？'],
        ['客服', 'Yes. Please confirm a contact method you can still use.', '可以，请确认一个你目前仍能使用的联系方式。'],
        ['失主', 'You can contact me through my account email.', '可以通过我的账号邮箱联系我。'],
      ]],
      ['找到的物品不匹配', '补充差异继续查找', [
        ['工作人员', 'This phone has a blue case. Is it yours?', '这部手机是蓝色保护壳，是你的吗？'],
        ['失主', 'No, mine has a black case and a red sticker.', '不是，我的是黑色壳，有红色贴纸。'],
        ['工作人员', 'Thank you. We will keep checking the records.', '谢谢，我们会继续查记录。'],
        ['失主', 'I appreciate it. Please let me know if there is an update.', '谢谢，有进展请告诉我。'],
      ]],
    ],
    practice: { substitutions: ['把 phone 换成 backpack，用颜色和标记描述背包。', '把 taxi 换成 train，说明遗落在列车。', '把 around two 换成 around four thirty，提供时间。'], responses: [['Could you describe it?', '黑色壳和红贴纸。', 'It has a black case with a small red sticker.'], ['It has not been found yet.', '请求有消息时通知。', 'Could you let me know if it turns up?'], ['Bring proof of ownership.', '询问需要什么。', 'What should I bring to prove it is mine?']], task: '报告遗失物，给出时间、地点和两个特征；找到疑似物品后确认身份与取回办法。' },
  }),
};
