import { defineLesson } from './lesson-format.js';

// These workplace scenarios are original extensions for everyday colleague communication.
export const workChapters = [
  ['W01', '认识同事和办公室寒暄', 'Getting to know colleagues', 'MessagesSquare', '职场日常', '自我介绍 · 午休闲聊 · 自然结束', "I'm still getting used to how things work here.", '我还在熟悉这里的工作方式。'],
  ['W02', '求助、确认和听不清时接话', 'Asking and clarifying', 'LifeBuoy', '职场日常', '请求帮助 · 补问细节 · 复述确认', 'Could you walk me through the process?', '能带我过一遍流程吗？'],
  ['W03', '安排任务、优先级和截止时间', 'Tasks and priorities', 'BookOpen', '职场日常', '明确交付 · 协商优先级 · 确认时间', 'Which one should I prioritize?', '我应该优先做哪一个？'],
  ['W04', '汇报进度、卡点和延期', 'Progress and blockers', 'SlidersHorizontal', '职场日常', '说明进度 · 报告卡点 · 更新预期', "I'm waiting for the final figures before I can finish.", '我得等最终数据才能完成。'],
  ['W05', '开会发言、不同意见和行动项', 'Speaking in meetings', 'MessagesSquare', '职场日常', '补充观点 · 礼貌质疑 · 确认行动项', 'I see your point, but I have a concern about the timing.', '我明白你的观点，但对时间安排有个顾虑。'],
  ['W06', '线上会议、工作消息和跟进', 'Calls and follow-ups', 'Headphones', '职场日常', '音视频问题 · 简洁消息 · 礼貌跟进', 'Just following up on the file I sent yesterday.', '跟进一下我昨天发的文件。'],
  ['W07', '征求反馈、说明修改和确认版本', 'Feedback and revisions', 'Receipt', '职场日常', '征求意见 · 确认修改范围 · 核对版本', 'Could you be more specific about what needs changing?', '能具体说说哪些地方需要修改吗？'],
  ['W08', '约时间、请假和工作交接', 'Schedules and handovers', 'Coffee', '职场日常', '约短会 · 请假安排 · 清楚交接', "I'll send a handover note before I leave.", '我离开前会发交接说明。'],
];

export const workplaceLessons = {
  W01: defineLesson('W01', {
    scenario: '第一周加入新团队，在茶水间认识同事。你在产品团队，对方在运营团队；周末话题保持轻松，对方忙时自然结束。',
    phrases: ['join the team 加入团队', 'be based in 在某地办公', 'get used to 逐渐适应', 'grab lunch 去吃午饭', 'settle in 适应新环境', 'get back to work 回去工作'],
    core: [
      ["Hi, I'm Alex. I joined the team this week.", '你好，我是 Alex，这周刚加入团队。', '我'],
      ['I work on the product team.', '我在产品团队工作。', '我'],
      ['Which team are you on?', '你在哪个团队？', '我'],
      ["I'm based in the Shanghai office.", '我在上海办公室工作。', '同事'],
      ['How are you settling in?', '你适应得怎么样？', '同事'],
      ["I'm still getting used to how things work here.", '我还在熟悉这里的工作方式。', '我', 'get used to 后接名词或动名词；与 used to do 表示过去习惯不同。'],
      ['Everyone has been really helpful.', '大家都很愿意帮忙。', '我'],
      ['Do you usually have lunch around here?', '你平时在这附近吃午饭吗？', '我'],
      ['Would you like to grab lunch together?', '要一起去吃午饭吗？', '同事', 'grab lunch 是同事间随意的说法，不一定表示吃得很匆忙。'],
      ['How was your weekend?', '周末过得怎么样？', '我'],
      ["Pretty quiet. I mostly stayed home.", '挺平静的，基本待在家。', '同事'],
      ["Nice talking to you. I'll let you get back to work.", '很高兴和你聊聊，我不耽误你工作了。', '我', '自然结束短聊；不需要等对方明确赶人才能收尾。'],
    ],
    dialogues: [
      ['茶水间认识同事', '简短介绍并接住对方提问', [
        ['我', "Hi, I'm Alex. I joined the product team this week.", '你好，我是 Alex，这周刚加入产品团队。'],
        ['同事', "Nice to meet you. I'm Sam, from operations.", '很高兴认识你，我是运营团队的 Sam。'],
        ['我', 'Nice to meet you too. Are you based here?', '我也很高兴认识你，你在这里办公吗？'],
        ['同事', 'Yes, most days. How are you settling in?', '是的，大部分时间在这里，你适应得怎么样？'],
        ['我', "I'm still learning how things work, but everyone has been helpful.", '还在熟悉工作方式，不过大家都很愿意帮忙。'],
        ['同事', 'Good to hear. Let me know if you need anything.', '那就好，需要帮忙就告诉我。'],
      ]],
      ['午休时轻松聊两句', '不追问私人细节', [
        ['我', 'How was your weekend?', '周末过得怎么样？'],
        ['同事', 'Pretty quiet. I mostly stayed home. How about yours?', '挺平静的，基本待在家，你呢？'],
        ['我', 'I went for a walk and caught up with a friend.', '我去散步，还和朋友聊了聊。'],
        ['同事', 'Sounds nice. Are you getting lunch now?', '听起来不错，你现在去吃午饭吗？'],
        ['我', 'Yes. Would you like to join me?', '对，要一起吗？'],
        ['同事', "Sure. Give me five minutes to finish this email.", '好，给我五分钟写完这封邮件。'],
      ]],
    ],
    branches: [
      ['对方正忙', '及时结束而不继续追问', [
        ['我', 'Do you have a minute to chat?', '有空聊一分钟吗？'],
        ['同事', "I'm about to join a call, actually.", '其实我马上要开个线上会。'],
        ['我', "No problem. I'll let you get back to it.", '没问题，那不耽误你了。'],
        ['同事', "Thanks. Let's catch up later.", '谢谢，我们晚点聊。'],
      ]],
      ['没听清姓名', '直接确认，避免假装记住', [
        ['同事', "Hi, I'm Samira.", '你好，我是 Samira。'],
        ['我', 'Sorry, could you say your name again?', '不好意思，能再说一遍你的名字吗？'],
        ['同事', 'Samira. You can call me Sam.', 'Samira，叫我 Sam 就行。'],
        ['我', "Thanks, Sam. I'm Alex. Nice to meet you.", '谢谢，Sam，我是 Alex，很高兴认识你。'],
      ]],
    ],
    practice: { substitutions: ['把 product team 换成 finance team，介绍财务团队身份。', '把 this week 换成 last month，调整入职时间。', '把 lunch 换成 a coffee，邀请喝咖啡。'], responses: [['How are you settling in?', '还在适应，但同事很帮忙。', "I'm still getting used to things, but everyone has been helpful."], ['How was your weekend?', '平静，在家休息。', 'Pretty quiet. I stayed home and relaxed.'], ["I'm about to join a call.", '自然结束。', "No problem. I'll let you get back to it."]], task: '用两句介绍自己，问一个与工作有关的问题，聊一个轻松话题；对方忙时及时收尾。' },
  }),
  W02: defineLesson('W02', {
    scenario: '第一次提交费用报销，不清楚上传流程。先询问同事是否有空，确认需要 PDF 小票；另练习没听清、听懂词却不懂要求时如何补问。',
    phrases: ['walk me through 带我逐步了解', 'get stuck 卡住', 'upload the receipt 上传小票', 'make sure 确保或确认', 'mean by 指的是', 'give an example 举例'],
    core: [
      ['Do you have a minute to help me with something?', '你有空帮我看个事吗？', '我'],
      ['Could you walk me through the process?', '能带我过一遍流程吗？', '我', 'walk someone through 指一步步讲解，不是只给一句最终答案。'],
      ["I'm not sure where to upload the receipt.", '我不确定在哪里上传小票。', '我'],
      ['Which step are you stuck on?', '你卡在哪一步？', '同事'],
      ['Could you say that again, a little more slowly?', '能再说一遍，稍微慢一点吗？', '我'],
      ['Sorry, which folder did you mean?', '不好意思，你指的是哪个文件夹？', '我'],
      ['What do you mean by a final version?', '你说的最终版是指什么？', '我', 'mean by 用于询问某个词或要求的具体含义；语气平和时是正常澄清。'],
      ['Could you give me an example?', '能举个例子吗？', '我'],
      ['Just to confirm, you need it as a PDF?', '确认一下，你需要 PDF 格式，对吗？', '我', '复述需要确认的格式，比笼统说 I understand 更能发现理解偏差。'],
      ["That's right. Then click Submit.", '没错，然后点击提交。', '同事'],
      ['I see. Let me try it myself.', '明白了，让我自己试一下。', '我'],
      ['Thanks, that clears it up.', '谢谢，这样就清楚了。', '我'],
    ],
    dialogues: [
      ['请同事讲报销流程', '指出具体卡点', [
        ['我', 'Do you have a minute to help me with my expense claim?', '有空帮我看一下费用报销吗？'],
        ['同事', 'Sure. Which step are you stuck on?', '可以，你卡在哪一步？'],
        ['我', "I'm not sure where to upload the receipt.", '我不确定在哪里上传小票。'],
        ['同事', 'Open the claim, then use the Attachments section.', '打开报销单，再用附件区域。'],
        ['我', 'Just to confirm, you need the receipt as a PDF?', '确认一下，小票需要 PDF 格式，对吗？'],
        ['同事', "Yes. Upload it there, then click Submit.", '对，在那里上传，再点击提交。'],
      ]],
      ['把抽象要求问具体', '先澄清，再确认理解', [
        ['同事', 'Please send me the final version of the summary.', '请把汇总的最终版发我。'],
        ['我', 'What do you mean by the final version?', '你说的最终版是指什么？'],
        ['同事', 'The one with the approved figures and no review comments.', '带已批准数据、没有审阅批注的那份。'],
        ['我', 'So I should update the figures and remove the comments before sending it?', '所以发送前要更新数据并去掉批注？'],
        ['同事', "Exactly. Keep the working copy separately.", '对，工作草稿另外保留。'],
        ['我', "Got it. Thanks, that clears it up.", '明白，谢谢，这样就清楚了。'],
      ]],
    ],
    branches: [
      ['对方现在没空', '约一个具体时间', [
        ['我', 'Could you help me check this form?', '能帮我看一下这张表吗？'],
        ['同事', "I'm in the middle of something. Can it wait?", '我现在正忙，可以等一下吗？'],
        ['我', 'Yes. Would ten minutes after lunch work?', '可以，午饭后抽十分钟可以吗？'],
        ['同事', 'Sure. Message me at one thirty.', '可以，一点半给我发消息。'],
      ]],
      ['只漏听一个位置', '补问局部信息', [
        ['同事', 'Save it in the monthly reports folder.', '存到月报文件夹里。'],
        ['我', 'Sorry, which folder did you say?', '不好意思，你刚说哪个文件夹？'],
        ['同事', 'Monthly reports, inside the Finance folder.', 'Finance 文件夹里的 Monthly reports。'],
        ['我', 'Monthly reports under Finance. Got it.', 'Finance 下面的 Monthly reports，明白了。'],
      ]],
    ],
    practice: { substitutions: ['把 receipt 换成 invoice，说明要上传发票。', '把 PDF 换成 spreadsheet，确认需要表格文件。', '把 folder 换成 column，只补问没听清的列。'], responses: [['Which step are you stuck on?', '卡在上传附件。', "I'm not sure how to upload the attachment."], ['Can it wait until after lunch?', '可以，确认时间。', 'Yes. Would one thirty work?'], ['Send the final version.', '问清最终版标准。', 'What do you mean by the final version?']], task: '请求帮助并说明卡点；漏听一次后只补问关键细节，再复述操作顺序。' },
  }),
  W03: defineLesson('W03', {
    scenario: '周二收到周报和演示稿两项任务。周报周三中午十二点前交，演示稿先交粗稿；新任务加入时协商先后顺序，不默默承诺全部按时完成。',
    phrases: ['prioritize 优先处理', 'a rough draft 粗稿', 'the scope 工作范围', 'by noon 中午前', 'move the deadline back 延后截止时间', 'end of day 当天结束前'],
    core: [
      ['What would you like me to work on first?', '你希望我先做什么？', '我'],
      ['Which one should I prioritize?', '我应该优先做哪一个？', '我', '用于多项任务同时出现时明确取舍，不是表示自己拒绝做任务。'],
      ['When do you need this by?', '你需要我什么时候交？', '我'],
      ['Could you clarify the scope?', '能明确一下范围吗？', '我'],
      ['Do you need a rough draft or a finished version?', '你要粗稿还是完成版？', '我'],
      ['Please send the report by noon tomorrow.', '请明天中午前发来报告。', '负责人'],
      ['By noon, do you mean twelve o’clock?', '中午前是指十二点前吗？', '我', 'by 表示最迟到该时间；重要节点确认具体时间和时区。'],
      ['I can finish the report, but the slides will take longer.', '报告能完成，但演示稿需要更久。', '我'],
      ['Could we move the deadline back to Friday?', '可以把截止时间延后到周五吗？', '我', 'back 指推迟；搭配具体日期能避免 move the deadline 的方向歧义。'],
      ['Please focus on the report first.', '请先集中做报告。', '负责人'],
      ["I'll send a draft for review before I finalize it.", '定稿前我会先发草稿供审阅。', '我'],
      ['Who should I send it to?', '我应该发给谁？', '我'],
    ],
    dialogues: [
      ['确认两项任务', '交付形式、顺序和截止时间', [
        ['负责人', 'Could you prepare the weekly report and the slides?', '能准备周报和演示稿吗？'],
        ['我', 'Sure. Which one should I prioritize?', '可以，先做哪一个？'],
        ['负责人', 'The report. Please send it by noon tomorrow.', '周报，请明天中午前发来。'],
        ['我', 'By noon, do you mean twelve o’clock? And do you need finished slides?', '是十二点前吗？演示稿要完成版吗？'],
        ['负责人', 'Yes, twelve. A rough draft of the slides by Friday is fine.', '对，十二点，演示稿周五交粗稿就行。'],
        ['我', "Got it. Report first, then a slide draft by Friday.", '明白，先周报，再周五交演示稿粗稿。'],
      ]],
      ['先确认范围', '避免按错误理解开工', [
        ['我', 'Could you clarify the scope of the report?', '能明确一下报告范围吗？'],
        ['负责人', 'Just the sales figures and the three main issues this week.', '只要销售数据和本周三个主要问题。'],
        ['我', 'Should I include individual customer details?', '需要客户个人明细吗？'],
        ['负责人', 'No, a summary is enough.', '不需要，汇总就够。'],
        ['我', "Okay. I'll send a draft to you before I finalize it.", '好，定稿前我先给你发草稿。'],
        ['负责人', 'Thanks. Keep it to two pages if possible.', '谢谢，可以的话控制在两页。'],
      ]],
    ],
    branches: [
      ['临时加新任务', '把取舍说出来', [
        ['负责人', 'Could you also finish this summary today?', '今天还能把这份汇总做完吗？'],
        ['我', "I'm working on the report due tomorrow. Which should come first?", '我正在做明天到期的报告，哪个优先？'],
        ['负责人', 'Do the summary first. We can move the report deadline to Thursday.', '先做汇总，报告截止时间可以改到周四。'],
        ['我', "Okay. I'll update the task list with the new deadline.", '好，我会在任务清单里更新截止时间。'],
      ]],
      ['截止时间含糊', '确认具体小时和时区', [
        ['负责人', 'Please send it by end of day.', '请今天结束前发来。'],
        ['我', 'Would five p.m. Shanghai time work?', '上海时间下午五点可以吗？'],
        ['负责人', 'Yes, five p.m. is fine.', '可以，下午五点就好。'],
        ['我', "Thanks. I'll have it ready by then.", '谢谢，我会在那之前准备好。'],
      ]],
    ],
    practice: { substitutions: ['把 report 换成 proposal，确认方案截止时间。', '把 noon tomorrow 换成 three p.m. on Thursday，说清节点。', '把 rough draft 换成 one-page outline，确认交付为一页提纲。'], responses: [['Can you also do this today?', '先确认优先级。', 'Which task should I prioritize?'], ['Send it by end of day.', '确认具体时间和时区。', 'Would five p.m. Shanghai time work?'], ['We just need a rough draft.', '复述交付要求。', 'Got it. A rough draft is enough for now.']], task: '把一个模糊任务问成清楚的交付：范围、形式、负责人和截止时间；临时加任务时协商取舍。' },
  }),
  W04: defineLesson('W04', {
    scenario: '周报结构和正文已写好，最终数据要等财务确认。原定周三中午提交；周二提前报告风险，承诺周三上午十点更新状态，而非保证一定完成。',
    phrases: ['on track 按计划推进', 'run into an issue 遇到问题', 'be blocked by 被某事卡住', 'an updated estimate 更新的预估', 'flag a risk 提前提醒风险', 'keep you posted 及时告知进展'],
    core: [
      ["Here's a quick update on the report.", '简短汇报一下报告的进度。', '我'],
      ["I've finished the main sections.", '我已完成主要部分。', '我'],
      ["I'm still working on the final checks.", '我还在做最后的检查。', '我'],
      ["We're on track for Wednesday.", '目前按周三完成的计划推进。', '我'],
      ["I've run into an issue with the figures.", '我在数据方面遇到了问题。', '我'],
      ["I'm waiting for the final figures before I can finish.", '我得等最终数据才能完成。', '我'],
      ['Is there anything blocking you?', '有什么卡住你的进度吗？', '负责人'],
      ['I wanted to flag this early.', '我想提前把这件事提出来。', '我', 'flag 指提醒别人注意；后面需要说明具体问题，而不只表达担心。'],
      ["I may need another day.", '我可能还需要一天。', '我', 'may 表达当前估计；需补充原因和下一次更新时间，不当作已获批准的延期。'],
      ["I'll send an updated estimate tomorrow morning.", '我会明早发更新后的时间预估。', '我'],
      ['Would a draft without the final figures be useful?', '先给不含最终数据的草稿有帮助吗？', '我'],
      ["I'll keep you posted.", '我会及时告诉你进展。', '我', '最好配一个具体更新时间，避免变成没有节点的承诺。'],
    ],
    dialogues: [
      ['报告进度和依赖', '完成项、未完成项、下一步', [
        ['负责人', 'How is the weekly report coming along?', '周报进展怎么样？'],
        ['我', "I've finished the main sections, but I'm waiting for the final figures.", '主要部分写完了，但还在等最终数据。'],
        ['负责人', 'Who are you waiting on?', '在等谁提供？'],
        ['我', 'Finance. They said they would update me this afternoon.', '财务，他们说今天下午给我消息。'],
        ['负责人', 'Please let me know if that affects the deadline.', '如果影响截止时间，请告诉我。'],
        ['我', "I will. I'll send a status update by ten tomorrow morning.", '会的，我会明早十点前更新状态。'],
      ]],
      ['提前提出延期风险', '区分预测和承诺', [
        ['我', 'I wanted to flag a risk with the Wednesday deadline.', '我想提前提醒一下周三截止时间的风险。'],
        ['负责人', 'What has changed?', '发生了什么变化？'],
        ['我', 'The figures need another review, so I may need one more day.', '数据还需要再审一遍，所以我可能多需要一天。'],
        ['负责人', 'Can you send the completed sections first?', '能先发已经完成的部分吗？'],
        ['我', "Yes. I'll label them as a draft and note what's missing.", '能，我会标成草稿并注明缺少的内容。'],
        ['负责人', 'Good. Send an updated estimate tomorrow morning too.', '好，也请明早给一个更新后的时间预估。'],
      ]],
    ],
    branches: [
      ['对方要求现在给明确时间', '把未知条件说清楚', [
        ['负责人', 'Can you guarantee it will be ready tomorrow?', '你能保证明天准备好吗？'],
        ['我', "Not yet. It depends on when the figures are confirmed.", '目前还不能，要看数据何时确认。'],
        ['负责人', 'When will you know more?', '什么时候能有更多信息？'],
        ['我', "By ten tomorrow morning. I'll update you then.", '明早十点前，到时我会更新。'],
      ]],
      ['发现此前提交的数字有误', '承认错误并给修正计划', [
        ['我', 'I found an error in the total I sent earlier.', '我发现之前发的总数有误。'],
        ['负责人', 'Does it affect the conclusion?', '会影响结论吗？'],
        ['我', "I'm checking that now. I'll send a corrected version by three.", '我正在核查，三点前发修正版。'],
        ['负责人', 'Please highlight what changed.', '请标明改了什么。'],
      ]],
    ],
    practice: { substitutions: ['把 final figures 换成 client approval，说明等待客户确认。', '把 by ten 换成 by two this afternoon，指定更新时间。', '把 main sections 换成 first draft，报告已完成粗稿。'], responses: [['Is anything blocking you?', '在等财务确认。', "I'm waiting for confirmation from Finance."], ['Can you guarantee tomorrow?', '不能，说明依赖。', 'Not yet. It depends on when the figures are confirmed.'], ['Can you send part of it first?', '答应，说明草稿状态。', "Yes. I'll label it as a draft and note what's missing."]], task: '用四句话汇报已完成、剩余工作、卡点和下次更新时间；预计延期时提前提出可行替代。' },
  }),
  W05: defineLesson('W05', {
    scenario: '团队讨论是否下周一发布一份新指南。你担心审阅时间不足，建议先做小范围试用，最后明确谁负责、何时完成、下一次如何确认。',
    phrases: ['add a point 补充一点', 'raise a concern 提出顾虑', 'a small pilot 小范围试点', 'action items 行动项', 'take ownership 负责推进', 'sum up 总结'],
    core: [
      ['Could I add something here?', '我能在这里补充一点吗？', '我'],
      ['I agree with the overall approach.', '我赞同整体思路。', '我'],
      ['I see your point, but I have a concern about the timing.', '我明白你的观点，但对时间安排有个顾虑。', '我', '先表明理解，再指出具体问题；不必为了礼貌假装同意。'],
      ['Could we look at another option?', '我们能看看另一个方案吗？', '我'],
      ['What if we started with a small pilot?', '如果先做小范围试点呢？', '我', 'What if 加过去式可以提出假设性建议，不表示试点已经发生。'],
      ['Could you explain the reasoning behind that?', '能解释一下这样做的理由吗？', '我'],
      ['What would that mean for the deadline?', '那会怎样影响截止时间？', '我'],
      ["Let's stay focused on the main issue.", '我们先集中讨论主要问题。', '主持人'],
      ['Who will take ownership of this?', '这件事由谁负责推进？', '主持人', 'ownership 在这里是对任务负责，不是财产所有权；最好配交付和期限。'],
      ['I can take that on.', '这件事我可以接。', '我'],
      ['Can we confirm the action items before we finish?', '结束前能确认一下行动项吗？', '我'],
      ['So the next step is to review the draft on Thursday.', '所以下一步是周四审阅草稿。', '我'],
    ],
    dialogues: [
      ['表达有理由的不同意见', '提出具体替代', [
        ['同事', 'I suggest we publish the guide next Monday.', '我建议下周一发布指南。'],
        ['我', 'I see your point, but I have a concern about the timing.', '我明白你的想法，不过对时间有个顾虑。'],
        ['同事', 'What is your main concern?', '主要顾虑是什么？'],
        ['我', 'We have not reviewed it with the support team yet. Could we run a small pilot first?', '还没和支持团队一起审阅过，能先做小范围试用吗？'],
        ['同事', 'That could work. How much time would you need?', '可以，需要多久？'],
        ['我', 'Two days for feedback, then we can decide whether it is ready.', '两天收反馈，然后再决定是否能发布。'],
      ]],
      ['确认会议行动项', '负责人与时间要落到句子里', [
        ['主持人', 'Can we confirm the action items?', '确认一下行动项好吗？'],
        ['我', "I'll prepare the pilot version by Wednesday afternoon.", '我周三下午前准备试用版。'],
        ['同事', "I'll ask the support team to review it on Thursday.", '我安排支持团队周四审阅。'],
        ['主持人', 'When should we check the feedback?', '什么时候看反馈？'],
        ['我', 'Friday at ten. Can you add that to the calendar?', '周五十点，能加到日历吗？'],
        ['主持人', "Yes. I'll send the notes with those owners and dates.", '可以，我会发会议记录，注明这些负责人和日期。'],
      ]],
    ],
    branches: [
      ['发言被打断', '礼貌保留自己的话轮', [
        ['同事', 'We should just move on to the launch plan.', '我们直接讨论发布计划吧。'],
        ['我', 'Could I finish this point first? It affects the launch date.', '我能先把这一点说完吗，它会影响发布日期。'],
        ['同事', 'Of course. Go ahead.', '当然，请继续。'],
        ['我', 'We still need the support review before we confirm a date.', '确认日期前还需要支持团队的审阅。'],
      ]],
      ['行动项没有负责人', '提出明确分配', [
        ['主持人', 'Someone should update the document.', '得有人更新文档。'],
        ['我', 'Can we agree on an owner and a deadline?', '能明确负责人和截止时间吗？'],
        ['同事', 'I can own it and send the update by Thursday noon.', '我可以负责，周四中午前发更新。'],
        ['我', "Thanks. I'll put that in the notes.", '谢谢，我会写进会议记录。'],
      ]],
    ],
    practice: { substitutions: ['把 timing 换成 cost，说明对成本的顾虑。', '把 guide 换成 training plan，讨论培训计划。', '把 Thursday noon 换成 Friday afternoon，确认行动项期限。'], responses: [['What is your concern?', '需要先让支持团队审阅。', 'We need the support team to review it first.'], ['Who can take this on?', '接下并给期限。', 'I can take it on and finish it by Thursday.'], ['Can we move on?', '请求先说完与决策有关的一点。', 'Could I finish this point first? It affects the decision.']], task: '表达一个赞同点和一个具体顾虑，提出替代方案，最后确认两个带负责人和时间的行动项。' },
  }),
  W06: defineLesson('W06', {
    scenario: '线上会议开始时麦克风未开启，分享文件时同事看不到画面；会后用工作消息跟进昨天发的文件，明确希望周四下午三点前得到确认。',
    phrases: ['be on mute 处于静音', 'cut out 声音断续', 'share the screen 共享屏幕', 'drop the link 发链接', 'follow up on 跟进', 'confirm receipt 确认收到'],
    core: [
      ['Can you hear me clearly?', '能听清我说话吗？', '我'],
      ["You're on mute.", '你的麦克风静音了。', '同事'],
      ['Your audio is cutting out.', '你的声音断断续续的。', '同事', 'cut out 描述声音中断；you’re on mute 则说明麦克风静音，问题不同。'],
      ['Could you repeat the last part?', '能重复最后那部分吗？', '我'],
      ["I'll turn off my camera and try again.", '我先关摄像头再试一下。', '我'],
      ['Can you see my screen now?', '现在能看到我的屏幕吗？', '我'],
      ["I'll drop the link in the chat.", '我把链接发到聊天里。', '我', 'drop the link 是较随意的工作聊天说法；也可以用 send the link。'],
      ['Just following up on the file I sent yesterday.', '跟进一下我昨天发的文件。', '我', '这是消息里常见的省略句；正式邮件可写 I’m following up on...。'],
      ['Could you confirm that you received it?', '能确认一下你收到了吗？', '我'],
      ['Do you need anything else from me?', '还需要我提供什么吗？', '我'],
      ['Could you let me know by three p.m. on Thursday?', '能在周四下午三点前告诉我吗？', '我'],
      ['Thanks for the update. That helps.', '谢谢更新，这很有帮助。', '我'],
    ],
    dialogues: [
      ['排查线上会议声音', '只重复断掉的部分', [
        ['同事', "You're on mute, Alex.", 'Alex，你的麦克风静音了。'],
        ['我', 'Thanks. Can you hear me now?', '谢谢，现在听得到吗？'],
        ['同事', 'Yes, but your audio is cutting out a little.', '能，不过声音有点断续。'],
        ['我', "I'll turn off my camera and try again.", '我关摄像头再试一下。'],
        ['同事', 'That is better. Could you repeat the last part?', '好些了，能重复最后那部分吗？'],
        ['我', 'Of course. I said the draft will be ready on Thursday.', '当然，我说草稿周四会准备好。'],
      ]],
      ['发消息礼貌跟进', '提出具体请求而不只催促', [
        ['我', 'Hi Sam, just following up on the file I sent yesterday. Did you receive it?', 'Sam，你好，跟进一下昨天发的文件，你收到了吗？'],
        ['同事', 'Yes, thanks. I have not reviewed it yet.', '收到了，谢谢，我还没看。'],
        ['我', 'No problem. Could you let me know by three p.m. on Thursday if the figures are correct?', '没问题，能在周四下午三点前告诉我数据是否正确吗？'],
        ['同事', 'Thursday works. Do you need comments in the file?', '周四可以，要直接在文件里批注吗？'],
        ['我', 'Yes, please. That would be helpful.', '是的，谢谢，那样很有帮助。'],
        ['同事', "Okay. I'll add comments and message you when I'm done.", '好，我会加批注，看完后发消息告诉你。'],
      ]],
    ],
    branches: [
      ['同事看不到共享画面', '给替代访问方式', [
        ['同事', "I can't see the document on your screen.", '我看不到你屏幕上的文档。'],
        ['我', "I'll share the document window instead of the whole screen.", '我改为共享文档窗口，而不是整个屏幕。'],
        ['同事', "It's still blank on my side.", '我这边还是空白。'],
        ['我', "I'll send the link in the chat so you can open it directly.", '我把链接发聊天里，你可以直接打开。'],
      ]],
      ['跟进后发现对方没权限', '确认对象并处理权限', [
        ['同事', 'I received the link, but I cannot access the file.', '我收到链接了，但打不开文件。'],
        ['我', 'Which work account are you signed in with?', '你用哪个工作账号登录的？'],
        ['同事', 'My company account.', '公司账号。'],
        ['我', "Thanks. I'll check the sharing permissions and send an updated link.", '谢谢，我会检查共享权限，再发更新后的链接。'],
      ]],
    ],
    practice: { substitutions: ['把 file 换成 meeting notes，跟进会议记录。', '把 Thursday 换成 Tuesday，给出新的回复期限。', '把 last part 换成 last number，补问最后一个数字。'], responses: [["You're on mute.", '开麦并确认声音。', 'Thanks. Can you hear me now?'], ['I have not reviewed it yet.', '给明确期限。', 'Could you let me know by Thursday afternoon?'], ['I cannot access the file.', '承诺检查权限。', "I'll check the sharing permissions."]], task: '处理一次音视频故障；会后写一条包含文件、希望对方做的事和回复期限的跟进消息。' },
  }),
  W07: defineLesson('W07', {
    scenario: '演示稿第二版正在审阅，同事说“开头需要更清楚”。你问清具体修改范围，保留原版本并另存第三版，最后确认对方看的是否为最新版。',
    phrases: ['take a look 看一下', 'be specific 说具体', 'revise the opening 修改开头', 'track changes 保留修订记录', 'the latest version 最新版', 'sign off 最终批准'],
    core: [
      ['Could you take a look at this draft?', '能看一下这份草稿吗？', '我'],
      ['I would appreciate your feedback on the opening.', '想请你对开头提些意见。', '我'],
      ['Does the main point come across clearly?', '主要观点表达得清楚吗？', '我'],
      ['Could you be more specific about what needs changing?', '能具体说说哪些地方需要修改吗？', '我'],
      ['Do you mean the wording or the structure?', '你是指措辞还是结构？', '我', 'wording 是用词，structure 是组织顺序；先确认修改维度再动手。'],
      ["I'll revise that section.", '我会修改那一部分。', '我'],
      ['Should I keep the examples?', '例子要保留吗？', '我'],
      ["I've made the changes we discussed.", '我们讨论的修改我已经做了。', '我'],
      ["I've highlighted the changes for you.", '我把修改处标出来了。', '我'],
      ['Are you looking at version three?', '你看的是第三版吗？', '我', '核对版本是排查不同理解的步骤，不把对方的反馈直接判为错误。'],
      ['Please use the latest version in the shared folder.', '请用共享文件夹里的最新版。', '我'],
      ['Who needs to sign off on the final version?', '最终版需要谁批准？', '我', 'sign off on 指最终批准或确认，不等于每次给意见。'],
    ],
    dialogues: [
      ['把反馈问具体', '区分结构与措辞', [
        ['我', 'Could you take a look at the opening of this draft?', '能看一下草稿的开头吗？'],
        ['同事', 'Sure. I think it needs to be clearer.', '可以，我觉得需要更清楚一些。'],
        ['我', 'Do you mean the wording or the structure?', '你是指措辞还是结构？'],
        ['同事', 'The structure. Put the recommendation before the background.', '结构，把建议放在背景介绍之前。'],
        ['我', 'Got it. Should I keep the two examples?', '明白，两个例子要保留吗？'],
        ['同事', 'Yes, but move them after the recommendation.', '要，但放到建议后面。'],
      ]],
      ['提交修改版', '说明改动并核对版本', [
        ['我', "I've made the changes we discussed and saved version three.", '讨论的修改做完了，已保存第三版。'],
        ['同事', 'Thanks. Where can I find it?', '谢谢，在哪里能找到？'],
        ['我', "In the shared folder. I've highlighted the opening changes.", '共享文件夹里，我标出了开头的修改。'],
        ['同事', 'Do the figures need another check?', '数据需要再检查一次吗？'],
        ['我', 'Yes. Finance still needs to confirm them before sign-off.', '需要，最终批准前财务还要确认。'],
        ['同事', "Okay. I'll review the structure while we wait.", '好，等确认时我先看结构。'],
      ]],
    ],
    branches: [
      ['两位同事意见冲突', '先对齐标准而不各改一遍', [
        ['我', 'I have two different suggestions for the opening.', '我收到了两种不同的开头建议。'],
        ['负责人', 'What is the difference?', '差别是什么？'],
        ['我', 'One puts the background first; the other starts with the recommendation. Which should I follow?', '一个先讲背景，一个先讲建议，我应该按哪个改？'],
        ['负责人', 'Start with the recommendation for this audience.', '针对这次受众，先讲建议。'],
      ]],
      ['同事在看旧版', '核对版本而非直接否定意见', [
        ['同事', 'I cannot see the new opening.', '我看不到新的开头。'],
        ['我', 'Are you looking at version two or version three?', '你看的是第二版还是第三版？'],
        ['同事', 'Version two. I opened the old attachment.', '第二版，我打开了旧附件。'],
        ['我', 'Please use version three in the shared folder. The opening is updated there.', '请用共享文件夹里的第三版，那份开头已更新。'],
      ]],
    ],
    practice: { substitutions: ['把 opening 换成 conclusion，征求结尾意见。', '把 wording or structure 换成 content or tone，确认内容还是语气。', '把 version three 换成 version four，核对新版。'], responses: [['It needs to be clearer.', '问清哪里不清楚。', 'Could you be more specific about what needs changing?'], ['I cannot see the changes.', '先确认版本。', 'Are you looking at the latest version?'], ['Keep the examples.', '复述修改方案。', "Got it. I'll keep them and move them after the recommendation."]], task: '征求一处具体反馈，问清修改范围，说明完成的改动；遇到冲突意见或旧版文件时先核对。' },
  }),
  W08: defineLesson('W08', {
    scenario: '你计划下周二请半天假，先按公司流程向负责人申请，再约同事周一下午交接。交接说明写明任务状态、周三截止时间和紧急联系人；请假是否批准以公司安排为准。',
    phrases: ['a quick catch-up 短时间沟通', 'take the morning off 上午请假', 'cover for someone 临时代班', 'handover notes 交接说明', 'be out of office 不在岗', 'urgent issues 紧急问题'],
    core: [
      ['Do you have fifteen minutes tomorrow?', '你明天有十五分钟吗？', '我'],
      ['What time works for you?', '你什么时间方便？', '我'],
      ['Could we move our catch-up to Monday afternoon?', '我们能把短会改到周一下午吗？', '我'],
      ["I'd like to request Tuesday morning off.", '我想申请周二上午请假。', '我', 'request 表示申请；还需按公司流程确认是否获批。'],
      ['Is there anything urgent I should finish first?', '有什么急事需要我先完成吗？', '我'],
      ['Could you cover the inbox while I am away?', '我不在时，你能帮忙看一下收件箱吗？', '我'],
      ["I'll send a handover note before I leave.", '我离开前会发交接说明。', '我'],
      ['The draft is ready, but approval is still pending.', '草稿已准备好，但还在等批准。', '我', 'pending 指尚未决定或处理完；ready 的草稿不等于已经可以发布。'],
      ['The deadline is Wednesday at noon.', '截止时间是周三中午十二点。', '我'],
      ['Please contact Sam for urgent issues.', '紧急问题请联系 Sam。', '我'],
      ["I'll be back on Tuesday afternoon.", '我周二下午回来。', '我'],
      ['Thanks for covering for me.', '谢谢你帮我代班。', '我', 'cover for 指代为处理工作；要先确认对方同意和职责范围。'],
    ],
    dialogues: [
      ['申请半天假', '说明时间并先安排工作', [
        ['我', "I'd like to request Tuesday morning off for an appointment.", '我想申请周二上午请假，有个预约。'],
        ['负责人', 'Have you checked the team schedule?', '你看过团队安排了吗？'],
        ['我', 'Yes. No meetings are scheduled then. Is there anything urgent I should finish first?', '看过，那个时段没安排会议，有什么急事要我先完成吗？'],
        ['负责人', 'Please finish the handover on Monday and submit the request in the system.', '请周一完成交接，并在系统提交申请。'],
        ['我', "Of course. I'll be back on Tuesday afternoon.", '当然，我周二下午回来。'],
        ['负责人', "Okay. I'll review the request once you submit it.", '好，你提交后我会审核。'],
      ]],
      ['交接进行中的任务', '状态、时间和联系人', [
        ['我', 'Could you cover the inbox on Tuesday morning?', '周二上午能帮我看一下收件箱吗？'],
        ['同事', 'Sure. Is there anything I should watch for?', '可以，有什么要留意的吗？'],
        ['我', 'The draft is ready, but approval is pending. The deadline is Wednesday at noon.', '草稿好了，但还在等批准，截止时间是周三中午十二点。'],
        ['同事', 'Who should I contact if there is an urgent question?', '有紧急问题时联系谁？'],
        ['我', "Sam. I'll include the link, status, and contact in the handover note.", 'Sam，我会在交接说明里写链接、状态和联系人。'],
        ['同事', "Great. I'll check the inbox and message you when you're back.", '好，我会看收件箱，等你回来再发消息同步。'],
      ]],
    ],
    branches: [
      ['交接时间冲突', '提出另一个可行时间', [
        ['同事', 'I have a meeting at two on Monday.', '周一两点我有会议。'],
        ['我', 'Would three thirty work for a fifteen-minute handover?', '三点半交接十五分钟可以吗？'],
        ['同事', 'Yes, that works.', '可以。'],
        ['我', "Thanks. I'll send the notes beforehand.", '谢谢，我会提前发说明。'],
      ]],
      ['请假时段团队人手不足', '协商安排但不默认获批', [
        ['负责人', 'We already have two people away on Tuesday morning.', '周二上午已经有两个人不在岗。'],
        ['我', 'Would taking Wednesday morning off be easier to arrange?', '改请周三上午是否更好安排？'],
        ['负责人', 'Possibly. Let me check the coverage first.', '可能，我先查一下人员安排。'],
        ['我', "Thanks. I'll wait for confirmation before changing the request.", '谢谢，我会等确认后再改申请。'],
      ]],
    ],
    practice: { substitutions: ['把 Tuesday morning 换成 Friday afternoon，申请另一时段。', '把 inbox 换成 support queue，商量代看支持工单。', '把 Wednesday at noon 换成 Thursday at four p.m.，说清交接期限。'], responses: [['What time works for you?', '提出周一三点半。', 'Would three thirty on Monday work?'], ['Who handles urgent issues?', '给联系人。', 'Please contact Sam for urgent issues.'], ['I can cover the inbox.', '感谢并承诺交接说明。', "Thanks. I'll send a handover note beforehand."]], task: '申请一个明确时段的假期，协商交接时间；把未完成事项、截止时间和联系人说明清楚。' },
  }),
};
